/* This file is generated, do not edit! */
package bpy.ops.mask;
@:pythonImport("bpy.ops.mask") extern class Mask_Module {
	static public var __builtins__ : Dynamic;
	static public var __cached__ : Dynamic;
	static public var __doc__ : Dynamic;
	static public var __file__ : Dynamic;
	static public var __loader__ : Dynamic;
	static public var __name__ : Dynamic;
	static public var __package__ : Dynamic;
	static public var __spec__ : Dynamic;
	static public function add_feather_vertex(?location:Dynamic):Dynamic;
	static public function add_feather_vertex_slide(?MASK_OT_add_feather_vertex:Dynamic, ?MASK_OT_slide_point:Dynamic):Dynamic;
	static public function add_vertex(?location:Dynamic):Dynamic;
	static public function add_vertex_slide(?MASK_OT_add_vertex:Dynamic, ?MASK_OT_slide_point:Dynamic):Dynamic;
	static public function copy_splines():Dynamic;
	static public function cyclic_toggle():Dynamic;
	static public function delete():Dynamic;
	static public function duplicate():Dynamic;
	static public function duplicate_move(?MASK_OT_duplicate:Dynamic, ?TRANSFORM_OT_translate:Dynamic):Dynamic;
	static public function feather_weight_clear():Dynamic;
	static public function handle_type_set(?type:Dynamic):Dynamic;
	static public function hide_view_clear(?select:Dynamic):Dynamic;
	static public function hide_view_set(?unselected:Dynamic):Dynamic;
	static public function layer_move(?direction:Dynamic):Dynamic;
	static public function layer_new(?name:Dynamic):Dynamic;
	static public function layer_remove():Dynamic;
	@:native("new")
	static public function _new(?name:Dynamic):Dynamic;
	static public function normals_make_consistent():Dynamic;
	static public function parent_clear():Dynamic;
	static public function parent_set():Dynamic;
	static public function paste_splines():Dynamic;
	static public function primitive_circle_add(?size:Dynamic, ?location:Dynamic):Dynamic;
	static public function primitive_square_add(?size:Dynamic, ?location:Dynamic):Dynamic;
	static public function select(?extend:Dynamic, ?deselect:Dynamic, ?toggle:Dynamic, ?location:Dynamic):Dynamic;
	static public function select_all(?action:Dynamic):Dynamic;
	static public function select_border(?xmin:Dynamic, ?xmax:Dynamic, ?ymin:Dynamic, ?ymax:Dynamic, ?deselect:Dynamic, ?extend:Dynamic):Dynamic;
	static public function select_circle(?x:Dynamic, ?y:Dynamic, ?radius:Dynamic, ?deselect:Dynamic):Dynamic;
	static public function select_lasso(?path:Dynamic, ?deselect:Dynamic, ?extend:Dynamic):Dynamic;
	static public function select_less():Dynamic;
	static public function select_linked():Dynamic;
	static public function select_linked_pick(?deselect:Dynamic):Dynamic;
	static public function select_more():Dynamic;
	static public function shape_key_clear():Dynamic;
	static public function shape_key_feather_reset():Dynamic;
	static public function shape_key_insert():Dynamic;
	static public function shape_key_rekey(?location:Dynamic, ?feather:Dynamic):Dynamic;
	static public function slide_point(?slide_feather:Dynamic, ?is_new_point:Dynamic):Dynamic;
	static public function slide_spline_curvature():Dynamic;
	static public function switch_direction():Dynamic;
}