/* This file is generated, do not edit! */
package bpy.ops.anim;
@:pythonImport("bpy.ops.anim") extern class Anim_Module {
	static public var __builtins__ : Dynamic;
	static public var __cached__ : Dynamic;
	static public var __doc__ : Dynamic;
	static public var __file__ : Dynamic;
	static public var __loader__ : Dynamic;
	static public var __name__ : Dynamic;
	static public var __package__ : Dynamic;
	static public var __spec__ : Dynamic;
	static public function change_frame(?frame:Dynamic, ?snap:Dynamic):Dynamic;
	static public function channel_select_keys(?extend:Dynamic):Dynamic;
	static public function channels_clean_empty():Dynamic;
	static public function channels_click(?extend:Dynamic, ?children_only:Dynamic):Dynamic;
	static public function channels_collapse(?all:Dynamic):Dynamic;
	static public function channels_delete():Dynamic;
	static public function channels_editable_toggle(?mode:Dynamic, ?type:Dynamic):Dynamic;
	static public function channels_expand(?all:Dynamic):Dynamic;
	static public function channels_fcurves_enable():Dynamic;
	static public function channels_find(?query:Dynamic):Dynamic;
	static public function channels_group(?name:Dynamic):Dynamic;
	static public function channels_move(?direction:Dynamic):Dynamic;
	static public function channels_rename():Dynamic;
	static public function channels_select_all(?action:Dynamic):Dynamic;
	static public function channels_select_border(?xmin:Dynamic, ?xmax:Dynamic, ?ymin:Dynamic, ?ymax:Dynamic, ?deselect:Dynamic, ?extend:Dynamic):Dynamic;
	static public function channels_setting_disable(?mode:Dynamic, ?type:Dynamic):Dynamic;
	static public function channels_setting_enable(?mode:Dynamic, ?type:Dynamic):Dynamic;
	static public function channels_setting_toggle(?mode:Dynamic, ?type:Dynamic):Dynamic;
	static public function channels_ungroup():Dynamic;
	static public function clear_useless_actions(?only_unused:Dynamic):Dynamic;
	static public function copy_driver_button():Dynamic;
	static public function driver_button_add():Dynamic;
	static public function driver_button_edit():Dynamic;
	static public function driver_button_remove(?all:Dynamic):Dynamic;
	static public function end_frame_set():Dynamic;
	static public function keyframe_clear_button(?all:Dynamic):Dynamic;
	static public function keyframe_clear_v3d():Dynamic;
	static public function keyframe_delete(?type:Dynamic, ?confirm_success:Dynamic):Dynamic;
	static public function keyframe_delete_button(?all:Dynamic):Dynamic;
	static public function keyframe_delete_v3d():Dynamic;
	static public function keyframe_insert(?type:Dynamic, ?confirm_success:Dynamic):Dynamic;
	static public function keyframe_insert_button(?all:Dynamic):Dynamic;
	static public function keyframe_insert_menu(?type:Dynamic, ?confirm_success:Dynamic, ?always_prompt:Dynamic):Dynamic;
	static public function keying_set_active_set(?type:Dynamic):Dynamic;
	static public function keying_set_add():Dynamic;
	static public function keying_set_export(?filepath:Dynamic, ?filter_folder:Dynamic, ?filter_text:Dynamic, ?filter_python:Dynamic):Dynamic;
	static public function keying_set_path_add():Dynamic;
	static public function keying_set_path_remove():Dynamic;
	static public function keying_set_remove():Dynamic;
	static public function keyingset_button_add(?all:Dynamic):Dynamic;
	static public function keyingset_button_remove():Dynamic;
	static public function paste_driver_button():Dynamic;
	static public function previewrange_clear():Dynamic;
	static public function previewrange_set(?xmin:Dynamic, ?xmax:Dynamic, ?ymin:Dynamic, ?ymax:Dynamic):Dynamic;
	static public function start_frame_set():Dynamic;
	static public function update_animated_transform_constraints(?use_convert_to_radians:Dynamic):Dynamic;
}