/* This file is generated, do not edit! */
package bpy.ops.node;
@:pythonImport("bpy.ops.node") extern class Node_Module {
	static public var __builtins__ : Dynamic;
	static public var __cached__ : Dynamic;
	static public var __doc__ : Dynamic;
	static public var __file__ : Dynamic;
	static public var __loader__ : Dynamic;
	static public var __name__ : Dynamic;
	static public var __package__ : Dynamic;
	static public var __spec__ : Dynamic;
	static public function add_and_link_node(?type:Dynamic, ?use_transform:Dynamic, ?settings:Dynamic, ?link_socket_index:Dynamic):Dynamic;
	static public function add_file(?filepath:Dynamic, ?filter_blender:Dynamic, ?filter_backup:Dynamic, ?filter_image:Dynamic, ?filter_movie:Dynamic, ?filter_python:Dynamic, ?filter_font:Dynamic, ?filter_sound:Dynamic, ?filter_text:Dynamic, ?filter_btx:Dynamic, ?filter_collada:Dynamic, ?filter_alembic:Dynamic, ?filter_folder:Dynamic, ?filter_blenlib:Dynamic, ?filemode:Dynamic, ?relative_path:Dynamic, ?show_multiview:Dynamic, ?use_multiview:Dynamic, ?display_type:Dynamic, ?sort_method:Dynamic, ?name:Dynamic):Dynamic;
	static public function add_mask(?name:Dynamic):Dynamic;
	static public function add_node(?type:Dynamic, ?use_transform:Dynamic, ?settings:Dynamic):Dynamic;
	static public function add_reroute(?path:Dynamic, ?cursor:Dynamic):Dynamic;
	static public function add_search(?type:Dynamic, ?use_transform:Dynamic, ?settings:Dynamic, ?node_item:Dynamic):Dynamic;
	static public function attach():Dynamic;
	static public function backimage_fit():Dynamic;
	static public function backimage_move():Dynamic;
	static public function backimage_sample():Dynamic;
	static public function backimage_zoom(?factor:Dynamic):Dynamic;
	static public function clear_viewer_border():Dynamic;
	static public function clipboard_copy():Dynamic;
	static public function clipboard_paste():Dynamic;
	static public function collapse_hide_unused_toggle():Dynamic;
	static public function cryptomatte_layer_add():Dynamic;
	static public function cryptomatte_layer_remove():Dynamic;
	static public function delete():Dynamic;
	static public function delete_reconnect():Dynamic;
	static public function detach():Dynamic;
	static public function detach_translate_attach(?NODE_OT_detach:Dynamic, ?TRANSFORM_OT_translate:Dynamic, ?NODE_OT_attach:Dynamic):Dynamic;
	static public function duplicate(?keep_inputs:Dynamic):Dynamic;
	static public function duplicate_move(?NODE_OT_duplicate:Dynamic, ?NODE_OT_translate_attach:Dynamic):Dynamic;
	static public function duplicate_move_keep_inputs(?NODE_OT_duplicate:Dynamic, ?NODE_OT_translate_attach:Dynamic):Dynamic;
	static public function find_node(?prev:Dynamic):Dynamic;
	static public function group_edit(?exit:Dynamic):Dynamic;
	static public function group_insert():Dynamic;
	static public function group_make():Dynamic;
	static public function group_separate(?type:Dynamic):Dynamic;
	static public function group_ungroup():Dynamic;
	static public function hide_socket_toggle():Dynamic;
	static public function hide_toggle():Dynamic;
	static public function insert_offset():Dynamic;
	static public function join():Dynamic;
	static public function link(?detach:Dynamic):Dynamic;
	static public function link_make(?replace:Dynamic):Dynamic;
	static public function link_viewer():Dynamic;
	static public function links_cut(?path:Dynamic, ?cursor:Dynamic):Dynamic;
	static public function links_detach():Dynamic;
	static public function move_detach_links(?NODE_OT_links_detach:Dynamic, ?TRANSFORM_OT_translate:Dynamic, ?NODE_OT_insert_offset:Dynamic):Dynamic;
	static public function move_detach_links_release(?NODE_OT_links_detach:Dynamic, ?NODE_OT_translate_attach:Dynamic):Dynamic;
	static public function mute_toggle():Dynamic;
	static public function new_node_tree(?type:Dynamic, ?name:Dynamic):Dynamic;
	static public function node_color_preset_add(?name:Dynamic, ?remove_name:Dynamic, ?remove_active:Dynamic):Dynamic;
	static public function node_copy_color():Dynamic;
	static public function options_toggle():Dynamic;
	static public function output_file_add_socket(?file_path:Dynamic):Dynamic;
	static public function output_file_move_active_socket(?direction:Dynamic):Dynamic;
	static public function output_file_remove_active_socket():Dynamic;
	static public function parent_set():Dynamic;
	static public function preview_toggle():Dynamic;
	static public function properties():Dynamic;
	static public function read_viewlayers():Dynamic;
	static public function render_changed():Dynamic;
	static public function resize():Dynamic;
	static public function select(?mouse_x:Dynamic, ?mouse_y:Dynamic, ?extend:Dynamic):Dynamic;
	static public function select_all(?action:Dynamic):Dynamic;
	static public function select_border(?xmin:Dynamic, ?xmax:Dynamic, ?ymin:Dynamic, ?ymax:Dynamic, ?deselect:Dynamic, ?extend:Dynamic, ?tweak:Dynamic):Dynamic;
	static public function select_circle(?x:Dynamic, ?y:Dynamic, ?radius:Dynamic, ?deselect:Dynamic):Dynamic;
	static public function select_grouped(?extend:Dynamic, ?type:Dynamic):Dynamic;
	static public function select_lasso(?path:Dynamic, ?deselect:Dynamic, ?extend:Dynamic):Dynamic;
	static public function select_link_viewer(?NODE_OT_select:Dynamic, ?NODE_OT_link_viewer:Dynamic):Dynamic;
	static public function select_linked_from():Dynamic;
	static public function select_linked_to():Dynamic;
	static public function select_same_type_step(?prev:Dynamic):Dynamic;
	static public function shader_script_update():Dynamic;
	static public function switch_view_update():Dynamic;
	static public function toolbar():Dynamic;
	static public function translate_attach(?TRANSFORM_OT_translate:Dynamic, ?NODE_OT_attach:Dynamic, ?NODE_OT_insert_offset:Dynamic):Dynamic;
	static public function translate_attach_remove_on_cancel(?TRANSFORM_OT_translate:Dynamic, ?NODE_OT_attach:Dynamic, ?NODE_OT_insert_offset:Dynamic):Dynamic;
	static public function tree_path_parent():Dynamic;
	static public function tree_socket_add(?in_out:Dynamic):Dynamic;
	static public function tree_socket_move(?direction:Dynamic):Dynamic;
	static public function tree_socket_remove():Dynamic;
	static public function view_all():Dynamic;
	static public function view_selected():Dynamic;
	static public function viewer_border(?xmin:Dynamic, ?xmax:Dynamic, ?ymin:Dynamic, ?ymax:Dynamic, ?deselect:Dynamic, ?extend:Dynamic):Dynamic;
}