/* This file is generated, do not edit! */
package bgl;
@:pythonImport("bgl") extern class Bgl_Module {
	static public var __builtins__ : Dynamic;
	static public var __cached__ : Dynamic;
	static public var __doc__ : Dynamic;
	static public var __file__ : Dynamic;
	static public var __loader__ : Dynamic;
	static public var __name__ : Dynamic;
	static public var __package__ : Dynamic;
	static public var __spec__ : Dynamic;
	static public function glAccum(op:Dynamic, value:Dynamic):Dynamic;
	static public function glActiveTexture(texture:Dynamic):Dynamic;
	static public function glAlphaFunc(func:Dynamic, ref:Dynamic):Dynamic;
	static public function glAreTexturesResident(n:Dynamic, textures:Dynamic, residences:Dynamic):Dynamic;
	static public function glAttachShader(program:Dynamic, shader:Dynamic):Dynamic;
	static public function glBegin(mode:Dynamic):Dynamic;
	static public function glBindTexture(target:Dynamic, texture:Dynamic):Dynamic;
	static public function glBitmap(width:Dynamic, height:Dynamic, xorig:Dynamic, yorig:Dynamic, xmove:Dynamic, ymove:Dynamic, bitmap:Dynamic):Dynamic;
	static public function glBlendFunc(sfactor:Dynamic, dfactor:Dynamic):Dynamic;
	static public function glCallList(list:Dynamic):Dynamic;
	static public function glCallLists(n:Dynamic, type:Dynamic, lists:Dynamic):Dynamic;
	static public function glClear(mask:Dynamic):Dynamic;
	static public function glClearAccum(red:Dynamic, green:Dynamic, blue:Dynamic, alpha:Dynamic):Dynamic;
	static public function glClearColor(red:Dynamic, green:Dynamic, blue:Dynamic, alpha:Dynamic):Dynamic;
	static public function glClearDepth(depth:Dynamic):Dynamic;
	static public function glClearIndex(c:Dynamic):Dynamic;
	static public function glClearStencil(s:Dynamic):Dynamic;
	static public function glClipPlane(plane:Dynamic, equation:Dynamic):Dynamic;
	static public function glColor(red:Dynamic, green:Dynamic, blue:Dynamic, alpha:Dynamic):Dynamic;
	static public function glColorMask(red:Dynamic, green:Dynamic, blue:Dynamic, alpha:Dynamic):Dynamic;
	static public function glColorMaterial(face:Dynamic, mode:Dynamic):Dynamic;
	static public function glCompileShader(shader:Dynamic):Dynamic;
	static public function glCopyPixels(x:Dynamic, y:Dynamic, width:Dynamic, height:Dynamic, type:Dynamic):Dynamic;
	static public function glCreateProgram():Dynamic;
	static public function glCreateShader(shaderType:Dynamic):Dynamic;
	static public function glCullFace(mode:Dynamic):Dynamic;
	static public function glDeleteLists(list:Dynamic, range:Dynamic):Dynamic;
	static public function glDeleteProgram(program:Dynamic):Dynamic;
	static public function glDeleteShader(shader:Dynamic):Dynamic;
	static public function glDeleteTextures(n:Dynamic, textures:Dynamic):Dynamic;
	static public function glDepthFunc(func:Dynamic):Dynamic;
	static public function glDepthMask(flag:Dynamic):Dynamic;
	static public function glDepthRange(zNear:Dynamic, zFar:Dynamic):Dynamic;
	static public function glDetachShader(program:Dynamic, shader:Dynamic):Dynamic;
	static public function glDisable(cap:Dynamic):Dynamic;
	static public function glDrawBuffer(mode:Dynamic):Dynamic;
	static public function glDrawPixels(width:Dynamic, height:Dynamic, format:Dynamic, type:Dynamic, pixels:Dynamic):Dynamic;
	static public function glEdgeFlag(flag:Dynamic):Dynamic;
	static public function glEnable(cap:Dynamic):Dynamic;
	static public function glEnd():Dynamic;
	static public function glEndList():Dynamic;
	static public function glEvalCoord(u:Dynamic, v:Dynamic):Dynamic;
	static public function glEvalMesh(mode:Dynamic, i1:Dynamic, i2:Dynamic):Dynamic;
	static public function glEvalPoint(i:Dynamic, j:Dynamic):Dynamic;
	static public function glFeedbackBuffer(size:Dynamic, type:Dynamic, buffer:Dynamic):Dynamic;
	static public function glFinish():Dynamic;
	static public function glFlush():Dynamic;
	static public function glFog(pname:Dynamic, param:Dynamic):Dynamic;
	static public function glFrontFace(mode:Dynamic):Dynamic;
	static public function glFrustum(left:Dynamic, right:Dynamic, bottom:Dynamic, top:Dynamic, zNear:Dynamic, zFar:Dynamic):Dynamic;
	static public function glGenLists(range:Dynamic):Dynamic;
	static public function glGenTextures(n:Dynamic, textures:Dynamic):Dynamic;
	static public function glGet(pname:Dynamic, param:Dynamic):Dynamic;
	static public function glGetAttachedShaders(program:Dynamic, maxCount:Dynamic, count:Dynamic, shaders:Dynamic):Dynamic;
	static public function glGetClipPlane(plane:Dynamic, equation:Dynamic):Dynamic;
	static public function glGetError():Dynamic;
	static public function glGetLight(light:Dynamic, pname:Dynamic, params:Dynamic):Dynamic;
	static public function glGetMap(target:Dynamic, query:Dynamic, v:Dynamic):Dynamic;
	static public function glGetMaterial(face:Dynamic, pname:Dynamic, params:Dynamic):Dynamic;
	static public function glGetPixelMap(map:Dynamic, values:Dynamic):Dynamic;
	static public function glGetPolygonStipple(mask:Dynamic):Dynamic;
	static public function glGetProgramInfoLog(program:Dynamic, maxLength:Dynamic, length:Dynamic, infoLog:Dynamic):Dynamic;
	static public function glGetProgramiv(program:Dynamic, pname:Dynamic, params:Dynamic):Dynamic;
	static public function glGetShaderInfoLog(program:Dynamic, maxLength:Dynamic, length:Dynamic, infoLog:Dynamic):Dynamic;
	static public function glGetShaderSource(shader:Dynamic, bufSize:Dynamic, length:Dynamic, source:Dynamic):Dynamic;
	static public function glGetString(name:Dynamic):Dynamic;
	static public function glGetTexEnv(target:Dynamic, pname:Dynamic, params:Dynamic):Dynamic;
	static public function glGetTexGen(coord:Dynamic, pname:Dynamic, params:Dynamic):Dynamic;
	static public function glGetTexImage(target:Dynamic, level:Dynamic, format:Dynamic, type:Dynamic, pixels:Dynamic):Dynamic;
	static public function glGetTexLevelParameter(target:Dynamic, level:Dynamic, pname:Dynamic, params:Dynamic):Dynamic;
	static public function glGetTexParameter(target:Dynamic, pname:Dynamic, params:Dynamic):Dynamic;
	static public function glHint(target:Dynamic, mode:Dynamic):Dynamic;
	static public function glIndex(c:Dynamic):Dynamic;
	static public function glIndexMask(mask:Dynamic):Dynamic;
	static public function glInitNames():Dynamic;
	static public function glIsEnabled(cap:Dynamic):Dynamic;
	static public function glIsList(list:Dynamic):Dynamic;
	static public function glIsProgram(program:Dynamic):Dynamic;
	static public function glIsShader(shader:Dynamic):Dynamic;
	static public function glIsTexture(texture:Dynamic):Dynamic;
	static public function glLight(light:Dynamic, pname:Dynamic, param:Dynamic):Dynamic;
	static public function glLightModel(pname:Dynamic, param:Dynamic):Dynamic;
	static public function glLineStipple(factor:Dynamic, pattern:Dynamic):Dynamic;
	static public function glLineWidth(width:Dynamic):Dynamic;
	static public function glLinkProgram(program:Dynamic):Dynamic;
	static public function glListBase(base:Dynamic):Dynamic;
	static public function glLoadIdentity():Dynamic;
	static public function glLoadMatrix(m:Dynamic):Dynamic;
	static public function glLoadName(name:Dynamic):Dynamic;
	static public function glLogicOp(opcode:Dynamic):Dynamic;
	static public function glMap1(target:Dynamic, u1:Dynamic, u2:Dynamic, stride:Dynamic, order:Dynamic, points:Dynamic):Dynamic;
	static public function glMap2(target:Dynamic, u1:Dynamic, u2:Dynamic, ustride:Dynamic, uorder:Dynamic, v1:Dynamic, v2:Dynamic, vstride:Dynamic, vorder:Dynamic, points:Dynamic):Dynamic;
	static public function glMapGrid(un:Dynamic, u1:Dynamic, u2:Dynamic, vn:Dynamic, v1:Dynamic, v2:Dynamic):Dynamic;
	static public function glMaterial(face:Dynamic, pname:Dynamic, params:Dynamic):Dynamic;
	static public function glMatrixMode(mode:Dynamic):Dynamic;
	static public function glMultMatrix(m:Dynamic):Dynamic;
	static public function glNewList(list:Dynamic, mode:Dynamic):Dynamic;
	static public function glNormal3(nx:Dynamic, ny:Dynamic, nz:Dynamic, v:Dynamic):Dynamic;
	static public function glOrtho(left:Dynamic, right:Dynamic, bottom:Dynamic, top:Dynamic, zNear:Dynamic, zFar:Dynamic):Dynamic;
	static public function glPassThrough(token:Dynamic):Dynamic;
	static public function glPixelMap(map:Dynamic, mapsize:Dynamic, values:Dynamic):Dynamic;
	static public function glPixelStore(pname:Dynamic, param:Dynamic):Dynamic;
	static public function glPixelTransfer(pname:Dynamic, param:Dynamic):Dynamic;
	static public function glPixelZoom(xfactor:Dynamic, yfactor:Dynamic):Dynamic;
	static public function glPointSize(size:Dynamic):Dynamic;
	static public function glPolygonMode(face:Dynamic, mode:Dynamic):Dynamic;
	static public function glPolygonOffset(factor:Dynamic, units:Dynamic):Dynamic;
	static public function glPolygonStipple(mask:Dynamic):Dynamic;
	static public function glPopAttrib():Dynamic;
	static public function glPopClientAttrib():Dynamic;
	static public function glPopMatrix():Dynamic;
	static public function glPopName():Dynamic;
	static public function glPrioritizeTextures(n:Dynamic, textures:Dynamic, priorities:Dynamic):Dynamic;
	static public function glPushAttrib(mask:Dynamic):Dynamic;
	static public function glPushClientAttrib(mask:Dynamic):Dynamic;
	static public function glPushMatrix():Dynamic;
	static public function glPushName(name:Dynamic):Dynamic;
	static public function glRasterPos(x:Dynamic, y:Dynamic, z:Dynamic, w:Dynamic):Dynamic;
	static public function glReadBuffer(mode:Dynamic):Dynamic;
	static public function glReadPixels(x:Dynamic, y:Dynamic, width:Dynamic, height:Dynamic, format:Dynamic, type:Dynamic, pixels:Dynamic):Dynamic;
	static public function glRect(x1:Dynamic, y1:Dynamic, x2:Dynamic, y2:Dynamic, v1:Dynamic, v2:Dynamic):Dynamic;
	static public function glRenderMode(mode:Dynamic):Dynamic;
	static public function glRotate(angle:Dynamic, x:Dynamic, y:Dynamic, z:Dynamic):Dynamic;
	static public function glScale(x:Dynamic, y:Dynamic, z:Dynamic):Dynamic;
	static public function glScissor(x:Dynamic, y:Dynamic, width:Dynamic, height:Dynamic):Dynamic;
	static public function glSelectBuffer(size:Dynamic, buffer:Dynamic):Dynamic;
	static public function glShadeModel(mode:Dynamic):Dynamic;
	static public function glShaderSource(shader:Dynamic, shader_string:Dynamic):Dynamic;
	static public function glStencilFunc(func:Dynamic, ref:Dynamic, mask:Dynamic):Dynamic;
	static public function glStencilMask(mask:Dynamic):Dynamic;
	static public function glStencilOp(fail:Dynamic, zfail:Dynamic, zpass:Dynamic):Dynamic;
	static public function glTexCoord(s:Dynamic, t:Dynamic, r:Dynamic, q:Dynamic, v:Dynamic):Dynamic;
	static public function glTexEnv(target:Dynamic, pname:Dynamic, param:Dynamic):Dynamic;
	static public function glTexGen(coord:Dynamic, pname:Dynamic, param:Dynamic):Dynamic;
	static public function glTexImage1D(target:Dynamic, level:Dynamic, internalformat:Dynamic, width:Dynamic, border:Dynamic, format:Dynamic, type:Dynamic, pixels:Dynamic):Dynamic;
	static public function glTexImage2D(target:Dynamic, level:Dynamic, internalformat:Dynamic, width:Dynamic, height:Dynamic, border:Dynamic, format:Dynamic, type:Dynamic, pixels:Dynamic):Dynamic;
	static public function glTexParameter(target:Dynamic, pname:Dynamic, param:Dynamic):Dynamic;
	static public function glTranslate(x:Dynamic, y:Dynamic, z:Dynamic):Dynamic;
	static public function glUseProgram(program:Dynamic):Dynamic;
	static public function glValidateProgram(program:Dynamic):Dynamic;
	static public function glVertex(x:Dynamic, y:Dynamic, z:Dynamic, w:Dynamic, v:Dynamic):Dynamic;
	static public function glViewport(x:Dynamic, y:Dynamic, width:Dynamic, height:Dynamic):Dynamic;
	static public function gluLookAt(eyex:Dynamic, eyey:Dynamic, eyez:Dynamic, centerx:Dynamic, centery:Dynamic, centerz:Dynamic, upx:Dynamic, upy:Dynamic, upz:Dynamic):Dynamic;
	static public function gluOrtho2D(left:Dynamic, right:Dynamic, bottom:Dynamic, top:Dynamic):Dynamic;
	static public function gluPerspective(fovY:Dynamic, aspect:Dynamic, zNear:Dynamic, zFar:Dynamic):Dynamic;
	static public function gluPickMatrix(x:Dynamic, y:Dynamic, width:Dynamic, height:Dynamic, viewport:Dynamic):Dynamic;
	static public function gluProject(objx:Dynamic, objy:Dynamic, objz:Dynamic, modelMatrix:Dynamic, projMatrix:Dynamic, viewport:Dynamic, winx:Dynamic, winy:Dynamic, winz:Dynamic):Dynamic;
	static public function gluUnProject(winx:Dynamic, winy:Dynamic, winz:Dynamic, modelMatrix:Dynamic, projMatrix:Dynamic, viewport:Dynamic, objx:Dynamic, objy:Dynamic, objz:Dynamic):Dynamic;
}