/* This file is generated, do not edit! */
package bpy.ops.paint;
@:pythonImport("bpy.ops.paint") extern class Paint_Module {
	static public var __builtins__ : Dynamic;
	static public var __cached__ : Dynamic;
	static public var __doc__ : Dynamic;
	static public var __file__ : Dynamic;
	static public var __loader__ : Dynamic;
	static public var __name__ : Dynamic;
	static public var __package__ : Dynamic;
	static public var __spec__ : Dynamic;
	static public function add_simple_uvs():Dynamic;
	static public function add_texture_paint_slot(?type:Dynamic, ?name:Dynamic, ?width:Dynamic, ?height:Dynamic, ?color:Dynamic, ?alpha:Dynamic, ?generated_type:Dynamic, ?float:Dynamic):Dynamic;
	static public function brush_colors_flip():Dynamic;
	static public function brush_select(?paint_mode:Dynamic, ?sculpt_tool:Dynamic, ?vertex_paint_tool:Dynamic, ?weight_paint_tool:Dynamic, ?texture_paint_tool:Dynamic, ?toggle:Dynamic, ?create_missing:Dynamic):Dynamic;
	static public function face_select_all(?action:Dynamic):Dynamic;
	static public function face_select_hide(?unselected:Dynamic):Dynamic;
	static public function face_select_linked():Dynamic;
	static public function face_select_linked_pick(?deselect:Dynamic):Dynamic;
	static public function face_select_reveal(?select:Dynamic):Dynamic;
	static public function grab_clone(?delta:Dynamic):Dynamic;
	static public function hide_show(?action:Dynamic, ?area:Dynamic, ?xmin:Dynamic, ?xmax:Dynamic, ?ymin:Dynamic, ?ymax:Dynamic):Dynamic;
	static public function image_from_view(?filepath:Dynamic):Dynamic;
	static public function image_paint(?stroke:Dynamic, ?mode:Dynamic):Dynamic;
	static public function mask_flood_fill(?mode:Dynamic, ?value:Dynamic):Dynamic;
	static public function mask_lasso_gesture(?path:Dynamic, ?mode:Dynamic, ?value:Dynamic):Dynamic;
	static public function project_image(?image:Dynamic):Dynamic;
	static public function sample_color(?location:Dynamic, ?merged:Dynamic, ?palette:Dynamic):Dynamic;
	static public function texture_paint_toggle():Dynamic;
	static public function vert_select_all(?action:Dynamic):Dynamic;
	static public function vert_select_ungrouped(?extend:Dynamic):Dynamic;
	static public function vertex_color_brightness_contrast(?brightness:Dynamic, ?contrast:Dynamic):Dynamic;
	static public function vertex_color_dirt(?blur_strength:Dynamic, ?blur_iterations:Dynamic, ?clean_angle:Dynamic, ?dirt_angle:Dynamic, ?dirt_only:Dynamic):Dynamic;
	static public function vertex_color_from_weight():Dynamic;
	static public function vertex_color_hsv(?h:Dynamic, ?s:Dynamic, ?v:Dynamic):Dynamic;
	static public function vertex_color_invert():Dynamic;
	static public function vertex_color_levels(?offset:Dynamic, ?gain:Dynamic):Dynamic;
	static public function vertex_color_set():Dynamic;
	static public function vertex_color_smooth():Dynamic;
	static public function vertex_paint(?stroke:Dynamic, ?mode:Dynamic):Dynamic;
	static public function vertex_paint_toggle():Dynamic;
	static public function weight_from_bones(?type:Dynamic):Dynamic;
	static public function weight_gradient(?type:Dynamic, ?xstart:Dynamic, ?xend:Dynamic, ?ystart:Dynamic, ?yend:Dynamic, ?cursor:Dynamic):Dynamic;
	static public function weight_paint(?stroke:Dynamic, ?mode:Dynamic):Dynamic;
	static public function weight_paint_toggle():Dynamic;
	static public function weight_sample():Dynamic;
	static public function weight_sample_group(?group:Dynamic):Dynamic;
	static public function weight_set():Dynamic;
}