/* This file is generated, do not edit! */
package bpy.ops.sequencer;
@:pythonImport("bpy.ops.sequencer") extern class Sequencer_Module {
	static public var __builtins__ : Dynamic;
	static public var __cached__ : Dynamic;
	static public var __doc__ : Dynamic;
	static public var __file__ : Dynamic;
	static public var __loader__ : Dynamic;
	static public var __name__ : Dynamic;
	static public var __package__ : Dynamic;
	static public var __spec__ : Dynamic;
	static public function change_effect_input(?swap:Dynamic):Dynamic;
	static public function change_effect_type(?type:Dynamic):Dynamic;
	static public function change_path(?filepath:Dynamic, ?directory:Dynamic, ?files:Dynamic, ?filter_blender:Dynamic, ?filter_backup:Dynamic, ?filter_image:Dynamic, ?filter_movie:Dynamic, ?filter_python:Dynamic, ?filter_font:Dynamic, ?filter_sound:Dynamic, ?filter_text:Dynamic, ?filter_btx:Dynamic, ?filter_collada:Dynamic, ?filter_alembic:Dynamic, ?filter_folder:Dynamic, ?filter_blenlib:Dynamic, ?filemode:Dynamic, ?relative_path:Dynamic, ?display_type:Dynamic, ?sort_method:Dynamic, ?use_placeholders:Dynamic):Dynamic;
	static public function copy():Dynamic;
	static public function crossfade_sounds():Dynamic;
	static public function cut(?frame:Dynamic, ?type:Dynamic, ?side:Dynamic):Dynamic;
	static public function cut_multicam(?camera:Dynamic):Dynamic;
	static public function deinterlace_selected_movies():Dynamic;
	static public function delete():Dynamic;
	static public function duplicate(?mode:Dynamic):Dynamic;
	static public function duplicate_move(?SEQUENCER_OT_duplicate:Dynamic, ?TRANSFORM_OT_seq_slide:Dynamic):Dynamic;
	static public function effect_strip_add(?frame_start:Dynamic, ?frame_end:Dynamic, ?channel:Dynamic, ?replace_sel:Dynamic, ?overlap:Dynamic, ?type:Dynamic, ?color:Dynamic):Dynamic;
	static public function enable_proxies(?proxy_25:Dynamic, ?proxy_50:Dynamic, ?proxy_75:Dynamic, ?proxy_100:Dynamic, ?overwrite:Dynamic):Dynamic;
	static public function export_subtitles(?filepath:Dynamic, ?check_existing:Dynamic, ?filter_blender:Dynamic, ?filter_backup:Dynamic, ?filter_image:Dynamic, ?filter_movie:Dynamic, ?filter_python:Dynamic, ?filter_font:Dynamic, ?filter_sound:Dynamic, ?filter_text:Dynamic, ?filter_btx:Dynamic, ?filter_collada:Dynamic, ?filter_alembic:Dynamic, ?filter_folder:Dynamic, ?filter_blenlib:Dynamic, ?filemode:Dynamic, ?display_type:Dynamic, ?sort_method:Dynamic):Dynamic;
	static public function gap_insert(?frames:Dynamic):Dynamic;
	static public function gap_remove(?all:Dynamic):Dynamic;
	static public function image_strip_add(?directory:Dynamic, ?files:Dynamic, ?filter_blender:Dynamic, ?filter_backup:Dynamic, ?filter_image:Dynamic, ?filter_movie:Dynamic, ?filter_python:Dynamic, ?filter_font:Dynamic, ?filter_sound:Dynamic, ?filter_text:Dynamic, ?filter_btx:Dynamic, ?filter_collada:Dynamic, ?filter_alembic:Dynamic, ?filter_folder:Dynamic, ?filter_blenlib:Dynamic, ?filemode:Dynamic, ?relative_path:Dynamic, ?show_multiview:Dynamic, ?use_multiview:Dynamic, ?display_type:Dynamic, ?sort_method:Dynamic, ?frame_start:Dynamic, ?frame_end:Dynamic, ?channel:Dynamic, ?replace_sel:Dynamic, ?overlap:Dynamic, ?use_placeholders:Dynamic):Dynamic;
	static public function images_separate(?length:Dynamic):Dynamic;
	static public function lock():Dynamic;
	static public function mask_strip_add(?frame_start:Dynamic, ?channel:Dynamic, ?replace_sel:Dynamic, ?overlap:Dynamic, ?mask:Dynamic):Dynamic;
	static public function meta_make():Dynamic;
	static public function meta_separate():Dynamic;
	static public function meta_toggle():Dynamic;
	static public function movie_strip_add(?filepath:Dynamic, ?files:Dynamic, ?filter_blender:Dynamic, ?filter_backup:Dynamic, ?filter_image:Dynamic, ?filter_movie:Dynamic, ?filter_python:Dynamic, ?filter_font:Dynamic, ?filter_sound:Dynamic, ?filter_text:Dynamic, ?filter_btx:Dynamic, ?filter_collada:Dynamic, ?filter_alembic:Dynamic, ?filter_folder:Dynamic, ?filter_blenlib:Dynamic, ?filemode:Dynamic, ?relative_path:Dynamic, ?show_multiview:Dynamic, ?use_multiview:Dynamic, ?display_type:Dynamic, ?sort_method:Dynamic, ?frame_start:Dynamic, ?channel:Dynamic, ?replace_sel:Dynamic, ?overlap:Dynamic, ?sound:Dynamic, ?use_framerate:Dynamic):Dynamic;
	static public function movieclip_strip_add(?frame_start:Dynamic, ?channel:Dynamic, ?replace_sel:Dynamic, ?overlap:Dynamic, ?clip:Dynamic):Dynamic;
	static public function mute(?unselected:Dynamic):Dynamic;
	static public function offset_clear():Dynamic;
	static public function paste():Dynamic;
	static public function properties():Dynamic;
	static public function reassign_inputs():Dynamic;
	static public function rebuild_proxy():Dynamic;
	static public function refresh_all():Dynamic;
	static public function reload(?adjust_length:Dynamic):Dynamic;
	static public function rendersize():Dynamic;
	static public function sample():Dynamic;
	static public function scene_strip_add(?frame_start:Dynamic, ?channel:Dynamic, ?replace_sel:Dynamic, ?overlap:Dynamic, ?scene:Dynamic):Dynamic;
	static public function select(?extend:Dynamic, ?linked_handle:Dynamic, ?left_right:Dynamic, ?linked_time:Dynamic):Dynamic;
	static public function select_active_side(?side:Dynamic):Dynamic;
	static public function select_all(?action:Dynamic):Dynamic;
	static public function select_border(?xmin:Dynamic, ?xmax:Dynamic, ?ymin:Dynamic, ?ymax:Dynamic, ?deselect:Dynamic, ?extend:Dynamic):Dynamic;
	static public function select_grouped(?type:Dynamic, ?extend:Dynamic, ?use_active_channel:Dynamic):Dynamic;
	static public function select_handles(?side:Dynamic):Dynamic;
	static public function select_less():Dynamic;
	static public function select_linked():Dynamic;
	static public function select_linked_pick(?extend:Dynamic):Dynamic;
	static public function select_more():Dynamic;
	static public function slip(?offset:Dynamic):Dynamic;
	static public function snap(?frame:Dynamic):Dynamic;
	static public function sound_strip_add(?filepath:Dynamic, ?files:Dynamic, ?filter_blender:Dynamic, ?filter_backup:Dynamic, ?filter_image:Dynamic, ?filter_movie:Dynamic, ?filter_python:Dynamic, ?filter_font:Dynamic, ?filter_sound:Dynamic, ?filter_text:Dynamic, ?filter_btx:Dynamic, ?filter_collada:Dynamic, ?filter_alembic:Dynamic, ?filter_folder:Dynamic, ?filter_blenlib:Dynamic, ?filemode:Dynamic, ?relative_path:Dynamic, ?display_type:Dynamic, ?sort_method:Dynamic, ?frame_start:Dynamic, ?channel:Dynamic, ?replace_sel:Dynamic, ?overlap:Dynamic, ?cache:Dynamic, ?mono:Dynamic):Dynamic;
	static public function strip_jump(?next:Dynamic, ?center:Dynamic):Dynamic;
	static public function strip_modifier_add(?type:Dynamic):Dynamic;
	static public function strip_modifier_copy(?type:Dynamic):Dynamic;
	static public function strip_modifier_move(?name:Dynamic, ?direction:Dynamic):Dynamic;
	static public function strip_modifier_remove(?name:Dynamic):Dynamic;
	static public function swap(?side:Dynamic):Dynamic;
	static public function swap_data():Dynamic;
	static public function swap_inputs():Dynamic;
	static public function unlock():Dynamic;
	static public function unmute(?unselected:Dynamic):Dynamic;
	static public function view_all():Dynamic;
	static public function view_all_preview():Dynamic;
	static public function view_frame():Dynamic;
	static public function view_ghost_border(?xmin:Dynamic, ?xmax:Dynamic, ?ymin:Dynamic, ?ymax:Dynamic):Dynamic;
	static public function view_selected():Dynamic;
	static public function view_toggle():Dynamic;
	static public function view_zoom_ratio(?ratio:Dynamic):Dynamic;
}