/* This file is generated, do not edit! */
package bpy.ops.nla;
@:pythonImport("bpy.ops.nla") extern class Nla_Module {
	static public var __builtins__ : Dynamic;
	static public var __cached__ : Dynamic;
	static public var __doc__ : Dynamic;
	static public var __file__ : Dynamic;
	static public var __loader__ : Dynamic;
	static public var __name__ : Dynamic;
	static public var __package__ : Dynamic;
	static public var __spec__ : Dynamic;
	static public function action_pushdown(?channel_index:Dynamic):Dynamic;
	static public function action_sync_length(?active:Dynamic):Dynamic;
	static public function action_unlink(?force_delete:Dynamic):Dynamic;
	static public function actionclip_add(?action:Dynamic):Dynamic;
	static public function apply_scale():Dynamic;
	static public function bake(?frame_start:Dynamic, ?frame_end:Dynamic, ?step:Dynamic, ?only_selected:Dynamic, ?visual_keying:Dynamic, ?clear_constraints:Dynamic, ?clear_parents:Dynamic, ?use_current_action:Dynamic, ?bake_types:Dynamic):Dynamic;
	static public function channels_click(?extend:Dynamic):Dynamic;
	static public function clear_scale():Dynamic;
	static public function click_select(?extend:Dynamic):Dynamic;
	static public function delete():Dynamic;
	static public function duplicate(?linked:Dynamic, ?mode:Dynamic):Dynamic;
	static public function fmodifier_add(?type:Dynamic, ?only_active:Dynamic):Dynamic;
	static public function fmodifier_copy():Dynamic;
	static public function fmodifier_paste(?only_active:Dynamic, ?replace:Dynamic):Dynamic;
	static public function make_single_user():Dynamic;
	static public function meta_add():Dynamic;
	static public function meta_remove():Dynamic;
	static public function move_down():Dynamic;
	static public function move_up():Dynamic;
	static public function mute_toggle():Dynamic;
	static public function previewrange_set():Dynamic;
	static public function properties():Dynamic;
	static public function select_all(?action:Dynamic):Dynamic;
	static public function select_border(?xmin:Dynamic, ?xmax:Dynamic, ?ymin:Dynamic, ?ymax:Dynamic, ?deselect:Dynamic, ?extend:Dynamic, ?axis_range:Dynamic):Dynamic;
	static public function select_leftright(?mode:Dynamic, ?extend:Dynamic):Dynamic;
	static public function selected_objects_add():Dynamic;
	static public function snap(?type:Dynamic):Dynamic;
	static public function soundclip_add():Dynamic;
	static public function split():Dynamic;
	static public function swap():Dynamic;
	static public function tracks_add(?above_selected:Dynamic):Dynamic;
	static public function tracks_delete():Dynamic;
	static public function transition_add():Dynamic;
	static public function tweakmode_enter(?isolate_action:Dynamic):Dynamic;
	static public function tweakmode_exit(?isolate_action:Dynamic):Dynamic;
	static public function view_all():Dynamic;
	static public function view_frame():Dynamic;
	static public function view_selected():Dynamic;
}