/* This file is generated, do not edit! */
package bpy.ops.object;
@:pythonImport("bpy.ops.object") extern class Object_Module {
	static public var __builtins__ : Dynamic;
	static public var __cached__ : Dynamic;
	static public var __doc__ : Dynamic;
	static public var __file__ : Dynamic;
	static public var __loader__ : Dynamic;
	static public var __name__ : Dynamic;
	static public var __package__ : Dynamic;
	static public var __spec__ : Dynamic;
	static public function add(?radius:Dynamic, ?type:Dynamic, ?view_align:Dynamic, ?enter_editmode:Dynamic, ?location:Dynamic, ?rotation:Dynamic):Dynamic;
	static public function add_named(?linked:Dynamic, ?name:Dynamic):Dynamic;
	static public function align(?bb_quality:Dynamic, ?align_mode:Dynamic, ?relative_to:Dynamic, ?align_axis:Dynamic):Dynamic;
	static public function anim_transforms_to_deltas():Dynamic;
	static public function armature_add(?radius:Dynamic, ?view_align:Dynamic, ?enter_editmode:Dynamic, ?location:Dynamic, ?rotation:Dynamic):Dynamic;
	static public function bake(?type:Dynamic, ?pass_filter:Dynamic, ?filepath:Dynamic, ?width:Dynamic, ?height:Dynamic, ?margin:Dynamic, ?use_selected_to_active:Dynamic, ?cage_extrusion:Dynamic, ?cage_object:Dynamic, ?normal_space:Dynamic, ?normal_r:Dynamic, ?normal_g:Dynamic, ?normal_b:Dynamic, ?save_mode:Dynamic, ?use_clear:Dynamic, ?use_cage:Dynamic, ?use_split_materials:Dynamic, ?use_automatic_name:Dynamic, ?uv_layer:Dynamic):Dynamic;
	static public function bake_image():Dynamic;
	static public function camera_add(?view_align:Dynamic, ?enter_editmode:Dynamic, ?location:Dynamic, ?rotation:Dynamic):Dynamic;
	static public function collection_add():Dynamic;
	static public function collection_instance_add(?name:Dynamic, ?collection:Dynamic, ?view_align:Dynamic, ?location:Dynamic, ?rotation:Dynamic):Dynamic;
	static public function collection_link(?collection:Dynamic):Dynamic;
	static public function collection_objects_select():Dynamic;
	static public function collection_remove():Dynamic;
	static public function collection_unlink():Dynamic;
	static public function constraint_add(?type:Dynamic):Dynamic;
	static public function constraint_add_with_targets(?type:Dynamic):Dynamic;
	static public function constraints_clear():Dynamic;
	static public function constraints_copy():Dynamic;
	static public function convert(?target:Dynamic, ?keep_original:Dynamic):Dynamic;
	static public function correctivesmooth_bind(?modifier:Dynamic):Dynamic;
	static public function data_transfer(?use_reverse_transfer:Dynamic, ?use_freeze:Dynamic, ?data_type:Dynamic, ?use_create:Dynamic, ?vert_mapping:Dynamic, ?edge_mapping:Dynamic, ?loop_mapping:Dynamic, ?poly_mapping:Dynamic, ?use_auto_transform:Dynamic, ?use_object_transform:Dynamic, ?use_max_distance:Dynamic, ?max_distance:Dynamic, ?ray_radius:Dynamic, ?islands_precision:Dynamic, ?layers_select_src:Dynamic, ?layers_select_dst:Dynamic, ?mix_mode:Dynamic, ?mix_factor:Dynamic):Dynamic;
	static public function datalayout_transfer(?modifier:Dynamic, ?data_type:Dynamic, ?use_delete:Dynamic, ?layers_select_src:Dynamic, ?layers_select_dst:Dynamic):Dynamic;
	static public function delete(?use_global:Dynamic):Dynamic;
	static public function drop_named_image(?filepath:Dynamic, ?relative_path:Dynamic, ?name:Dynamic, ?view_align:Dynamic, ?location:Dynamic, ?rotation:Dynamic):Dynamic;
	static public function drop_named_material(?name:Dynamic):Dynamic;
	static public function dupli_offset_from_cursor():Dynamic;
	static public function duplicate(?linked:Dynamic, ?mode:Dynamic):Dynamic;
	static public function duplicate_move(?OBJECT_OT_duplicate:Dynamic, ?TRANSFORM_OT_translate:Dynamic):Dynamic;
	static public function duplicate_move_linked(?OBJECT_OT_duplicate:Dynamic, ?TRANSFORM_OT_translate:Dynamic):Dynamic;
	static public function duplicates_make_real(?use_base_parent:Dynamic, ?use_hierarchy:Dynamic):Dynamic;
	static public function editmode_toggle():Dynamic;
	static public function effector_add(?type:Dynamic, ?radius:Dynamic, ?view_align:Dynamic, ?enter_editmode:Dynamic, ?location:Dynamic, ?rotation:Dynamic):Dynamic;
	static public function empty_add(?type:Dynamic, ?radius:Dynamic, ?view_align:Dynamic, ?location:Dynamic, ?rotation:Dynamic):Dynamic;
	static public function explode_refresh(?modifier:Dynamic):Dynamic;
	static public function face_map_add():Dynamic;
	static public function face_map_assign():Dynamic;
	static public function face_map_deselect():Dynamic;
	static public function face_map_move(?direction:Dynamic):Dynamic;
	static public function face_map_remove():Dynamic;
	static public function face_map_remove_from():Dynamic;
	static public function face_map_select():Dynamic;
	static public function forcefield_toggle():Dynamic;
	static public function gpencil_add(?radius:Dynamic, ?view_align:Dynamic, ?location:Dynamic, ?rotation:Dynamic, ?type:Dynamic):Dynamic;
	static public function gpencil_modifier_add(?type:Dynamic):Dynamic;
	static public function gpencil_modifier_apply(?apply_as:Dynamic, ?modifier:Dynamic):Dynamic;
	static public function gpencil_modifier_copy(?modifier:Dynamic):Dynamic;
	static public function gpencil_modifier_move_down(?modifier:Dynamic):Dynamic;
	static public function gpencil_modifier_move_up(?modifier:Dynamic):Dynamic;
	static public function gpencil_modifier_remove(?modifier:Dynamic):Dynamic;
	static public function hide_collection(?collection_index:Dynamic):Dynamic;
	static public function hide_render_clear_all():Dynamic;
	static public function hide_view_clear(?select:Dynamic):Dynamic;
	static public function hide_view_set(?unselected:Dynamic):Dynamic;
	static public function hook_add_newob():Dynamic;
	static public function hook_add_selob(?use_bone:Dynamic):Dynamic;
	static public function hook_assign(?modifier:Dynamic):Dynamic;
	static public function hook_recenter(?modifier:Dynamic):Dynamic;
	static public function hook_remove(?modifier:Dynamic):Dynamic;
	static public function hook_reset(?modifier:Dynamic):Dynamic;
	static public function hook_select(?modifier:Dynamic):Dynamic;
	static public function isolate_type_render():Dynamic;
	static public function join():Dynamic;
	static public function join_shapes():Dynamic;
	static public function join_uvs():Dynamic;
	static public function laplaciandeform_bind(?modifier:Dynamic):Dynamic;
	static public function light_add(?type:Dynamic, ?radius:Dynamic, ?view_align:Dynamic, ?location:Dynamic, ?rotation:Dynamic):Dynamic;
	static public function lightprobe_add(?type:Dynamic, ?radius:Dynamic, ?view_align:Dynamic, ?enter_editmode:Dynamic, ?location:Dynamic, ?rotation:Dynamic):Dynamic;
	static public function link_to_collection(?collection_index:Dynamic, ?is_new:Dynamic, ?new_collection_name:Dynamic):Dynamic;
	static public function location_clear(?clear_delta:Dynamic):Dynamic;
	static public function make_dupli_face():Dynamic;
	static public function make_links_data(?type:Dynamic):Dynamic;
	static public function make_links_scene(?scene:Dynamic):Dynamic;
	static public function make_local(?type:Dynamic):Dynamic;
	static public function make_override_static(?object:Dynamic):Dynamic;
	static public function make_single_user(?type:Dynamic, ?object:Dynamic, ?obdata:Dynamic, ?material:Dynamic, ?animation:Dynamic):Dynamic;
	static public function material_slot_add():Dynamic;
	static public function material_slot_assign():Dynamic;
	static public function material_slot_copy():Dynamic;
	static public function material_slot_deselect():Dynamic;
	static public function material_slot_move(?direction:Dynamic):Dynamic;
	static public function material_slot_remove():Dynamic;
	static public function material_slot_select():Dynamic;
	static public function meshdeform_bind(?modifier:Dynamic):Dynamic;
	static public function metaball_add(?type:Dynamic, ?radius:Dynamic, ?view_align:Dynamic, ?enter_editmode:Dynamic, ?location:Dynamic, ?rotation:Dynamic):Dynamic;
	static public function mode_set(?mode:Dynamic, ?toggle:Dynamic):Dynamic;
	static public function mode_set_or_submode(?mode:Dynamic, ?toggle:Dynamic):Dynamic;
	static public function modifier_add(?type:Dynamic):Dynamic;
	static public function modifier_apply(?apply_as:Dynamic, ?modifier:Dynamic):Dynamic;
	static public function modifier_convert(?modifier:Dynamic):Dynamic;
	static public function modifier_copy(?modifier:Dynamic):Dynamic;
	static public function modifier_move_down(?modifier:Dynamic):Dynamic;
	static public function modifier_move_up(?modifier:Dynamic):Dynamic;
	static public function modifier_remove(?modifier:Dynamic):Dynamic;
	static public function move_to_collection(?collection_index:Dynamic, ?is_new:Dynamic, ?new_collection_name:Dynamic):Dynamic;
	static public function multires_base_apply(?modifier:Dynamic):Dynamic;
	static public function multires_external_pack():Dynamic;
	static public function multires_external_save(?filepath:Dynamic, ?check_existing:Dynamic, ?filter_blender:Dynamic, ?filter_backup:Dynamic, ?filter_image:Dynamic, ?filter_movie:Dynamic, ?filter_python:Dynamic, ?filter_font:Dynamic, ?filter_sound:Dynamic, ?filter_text:Dynamic, ?filter_btx:Dynamic, ?filter_collada:Dynamic, ?filter_alembic:Dynamic, ?filter_folder:Dynamic, ?filter_blenlib:Dynamic, ?filemode:Dynamic, ?relative_path:Dynamic, ?display_type:Dynamic, ?sort_method:Dynamic, ?modifier:Dynamic):Dynamic;
	static public function multires_higher_levels_delete(?modifier:Dynamic):Dynamic;
	static public function multires_reshape(?modifier:Dynamic):Dynamic;
	static public function multires_subdivide(?modifier:Dynamic):Dynamic;
	static public function ocean_bake(?modifier:Dynamic, ?free:Dynamic):Dynamic;
	static public function origin_clear():Dynamic;
	static public function origin_set(?type:Dynamic, ?center:Dynamic):Dynamic;
	static public function parent_clear(?type:Dynamic):Dynamic;
	static public function parent_no_inverse_set():Dynamic;
	static public function parent_set(?type:Dynamic, ?xmirror:Dynamic, ?keep_transform:Dynamic):Dynamic;
	static public function particle_system_add():Dynamic;
	static public function particle_system_remove():Dynamic;
	static public function paths_calculate(?start_frame:Dynamic, ?end_frame:Dynamic):Dynamic;
	static public function paths_clear(?only_selected:Dynamic):Dynamic;
	static public function paths_range_update():Dynamic;
	static public function paths_update():Dynamic;
	static public function posemode_toggle():Dynamic;
	static public function proxy_make(?object:Dynamic):Dynamic;
	static public function quick_explode(?style:Dynamic, ?amount:Dynamic, ?frame_duration:Dynamic, ?frame_start:Dynamic, ?frame_end:Dynamic, ?velocity:Dynamic, ?fade:Dynamic):Dynamic;
	static public function quick_fluid(?style:Dynamic, ?initial_velocity:Dynamic, ?show_flows:Dynamic, ?start_baking:Dynamic):Dynamic;
	static public function quick_fur(?density:Dynamic, ?view_percentage:Dynamic, ?length:Dynamic):Dynamic;
	static public function quick_smoke(?style:Dynamic, ?show_flows:Dynamic):Dynamic;
	static public function randomize_transform(?random_seed:Dynamic, ?use_delta:Dynamic, ?use_loc:Dynamic, ?loc:Dynamic, ?use_rot:Dynamic, ?rot:Dynamic, ?use_scale:Dynamic, ?scale_even:Dynamic, ?scale:Dynamic):Dynamic;
	static public function rotation_clear(?clear_delta:Dynamic):Dynamic;
	static public function scale_clear(?clear_delta:Dynamic):Dynamic;
	static public function select_all(?action:Dynamic):Dynamic;
	static public function select_by_type(?extend:Dynamic, ?type:Dynamic):Dynamic;
	static public function select_camera(?extend:Dynamic):Dynamic;
	static public function select_grouped(?extend:Dynamic, ?type:Dynamic):Dynamic;
	static public function select_hierarchy(?direction:Dynamic, ?extend:Dynamic):Dynamic;
	static public function select_less():Dynamic;
	static public function select_linked(?extend:Dynamic, ?type:Dynamic):Dynamic;
	static public function select_mirror(?extend:Dynamic):Dynamic;
	static public function select_more():Dynamic;
	static public function select_pattern(?pattern:Dynamic, ?case_sensitive:Dynamic, ?extend:Dynamic):Dynamic;
	static public function select_random(?percent:Dynamic, ?seed:Dynamic, ?action:Dynamic):Dynamic;
	static public function select_same_collection(?collection:Dynamic):Dynamic;
	static public function shade_flat():Dynamic;
	static public function shade_smooth():Dynamic;
	static public function shaderfx_add(?type:Dynamic):Dynamic;
	static public function shaderfx_move_down(?shaderfx:Dynamic):Dynamic;
	static public function shaderfx_move_up(?shaderfx:Dynamic):Dynamic;
	static public function shaderfx_remove(?shaderfx:Dynamic):Dynamic;
	static public function shape_key_add(?from_mix:Dynamic):Dynamic;
	static public function shape_key_clear():Dynamic;
	static public function shape_key_mirror(?use_topology:Dynamic):Dynamic;
	static public function shape_key_move(?type:Dynamic):Dynamic;
	static public function shape_key_remove(?all:Dynamic):Dynamic;
	static public function shape_key_retime():Dynamic;
	static public function shape_key_transfer(?mode:Dynamic, ?use_clamp:Dynamic):Dynamic;
	static public function skin_armature_create(?modifier:Dynamic):Dynamic;
	static public function skin_loose_mark_clear(?action:Dynamic):Dynamic;
	static public function skin_radii_equalize():Dynamic;
	static public function skin_root_mark():Dynamic;
	static public function slow_parent_clear():Dynamic;
	static public function slow_parent_set():Dynamic;
	static public function speaker_add(?view_align:Dynamic, ?enter_editmode:Dynamic, ?location:Dynamic, ?rotation:Dynamic):Dynamic;
	static public function subdivision_set(?level:Dynamic, ?relative:Dynamic):Dynamic;
	static public function surfacedeform_bind(?modifier:Dynamic):Dynamic;
	static public function text_add(?radius:Dynamic, ?view_align:Dynamic, ?enter_editmode:Dynamic, ?location:Dynamic, ?rotation:Dynamic):Dynamic;
	static public function track_clear(?type:Dynamic):Dynamic;
	static public function track_set(?type:Dynamic):Dynamic;
	static public function transform_apply(?location:Dynamic, ?rotation:Dynamic, ?scale:Dynamic, ?properties:Dynamic):Dynamic;
	static public function transform_axis_target():Dynamic;
	static public function transforms_to_deltas(?mode:Dynamic, ?reset_values:Dynamic):Dynamic;
	static public function unlink_data():Dynamic;
	static public function vertex_group_add():Dynamic;
	static public function vertex_group_assign():Dynamic;
	static public function vertex_group_assign_new():Dynamic;
	static public function vertex_group_clean(?group_select_mode:Dynamic, ?limit:Dynamic, ?keep_single:Dynamic):Dynamic;
	static public function vertex_group_copy():Dynamic;
	static public function vertex_group_copy_to_linked():Dynamic;
	static public function vertex_group_copy_to_selected():Dynamic;
	static public function vertex_group_deselect():Dynamic;
	static public function vertex_group_fix(?dist:Dynamic, ?strength:Dynamic, ?accuracy:Dynamic):Dynamic;
	static public function vertex_group_invert(?group_select_mode:Dynamic, ?auto_assign:Dynamic, ?auto_remove:Dynamic):Dynamic;
	static public function vertex_group_levels(?group_select_mode:Dynamic, ?offset:Dynamic, ?gain:Dynamic):Dynamic;
	static public function vertex_group_limit_total(?group_select_mode:Dynamic, ?limit:Dynamic):Dynamic;
	static public function vertex_group_lock(?action:Dynamic):Dynamic;
	static public function vertex_group_mirror(?mirror_weights:Dynamic, ?flip_group_names:Dynamic, ?all_groups:Dynamic, ?use_topology:Dynamic):Dynamic;
	static public function vertex_group_move(?direction:Dynamic):Dynamic;
	static public function vertex_group_normalize():Dynamic;
	static public function vertex_group_normalize_all(?group_select_mode:Dynamic, ?lock_active:Dynamic):Dynamic;
	static public function vertex_group_quantize(?group_select_mode:Dynamic, ?steps:Dynamic):Dynamic;
	static public function vertex_group_remove(?all:Dynamic, ?all_unlocked:Dynamic):Dynamic;
	static public function vertex_group_remove_from(?use_all_groups:Dynamic, ?use_all_verts:Dynamic):Dynamic;
	static public function vertex_group_select():Dynamic;
	static public function vertex_group_set_active(?group:Dynamic):Dynamic;
	static public function vertex_group_smooth(?group_select_mode:Dynamic, ?factor:Dynamic, ?repeat:Dynamic, ?expand:Dynamic):Dynamic;
	static public function vertex_group_sort(?sort_type:Dynamic):Dynamic;
	static public function vertex_parent_set():Dynamic;
	static public function vertex_weight_copy():Dynamic;
	static public function vertex_weight_delete(?weight_group:Dynamic):Dynamic;
	static public function vertex_weight_normalize_active_vertex():Dynamic;
	static public function vertex_weight_paste(?weight_group:Dynamic):Dynamic;
	static public function vertex_weight_set_active(?weight_group:Dynamic):Dynamic;
	static public function visual_transform_apply():Dynamic;
}