/* This file is generated, do not edit! */
package bpy.ops.curve;
@:pythonImport("bpy.ops.curve") extern class Curve_Module {
	static public var __builtins__ : Dynamic;
	static public var __cached__ : Dynamic;
	static public var __doc__ : Dynamic;
	static public var __file__ : Dynamic;
	static public var __loader__ : Dynamic;
	static public var __name__ : Dynamic;
	static public var __package__ : Dynamic;
	static public var __spec__ : Dynamic;
	static public function cyclic_toggle(?direction:Dynamic):Dynamic;
	static public function de_select_first():Dynamic;
	static public function de_select_last():Dynamic;
	static public function decimate(?ratio:Dynamic):Dynamic;
	static public function delete(?type:Dynamic):Dynamic;
	static public function dissolve_verts():Dynamic;
	static public function draw(?error_threshold:Dynamic, ?fit_method:Dynamic, ?corner_angle:Dynamic, ?use_cyclic:Dynamic, ?stroke:Dynamic, ?wait_for_input:Dynamic):Dynamic;
	static public function duplicate():Dynamic;
	static public function duplicate_move(?CURVE_OT_duplicate:Dynamic, ?TRANSFORM_OT_translate:Dynamic):Dynamic;
	static public function extrude(?mode:Dynamic):Dynamic;
	static public function extrude_move(?CURVE_OT_extrude:Dynamic, ?TRANSFORM_OT_translate:Dynamic):Dynamic;
	static public function handle_type_set(?type:Dynamic):Dynamic;
	static public function hide(?unselected:Dynamic):Dynamic;
	static public function make_segment():Dynamic;
	static public function match_texture_space():Dynamic;
	static public function normals_make_consistent(?calc_length:Dynamic):Dynamic;
	static public function primitive_bezier_circle_add(?radius:Dynamic, ?view_align:Dynamic, ?enter_editmode:Dynamic, ?location:Dynamic, ?rotation:Dynamic):Dynamic;
	static public function primitive_bezier_curve_add(?radius:Dynamic, ?view_align:Dynamic, ?enter_editmode:Dynamic, ?location:Dynamic, ?rotation:Dynamic):Dynamic;
	static public function primitive_nurbs_circle_add(?radius:Dynamic, ?view_align:Dynamic, ?enter_editmode:Dynamic, ?location:Dynamic, ?rotation:Dynamic):Dynamic;
	static public function primitive_nurbs_curve_add(?radius:Dynamic, ?view_align:Dynamic, ?enter_editmode:Dynamic, ?location:Dynamic, ?rotation:Dynamic):Dynamic;
	static public function primitive_nurbs_path_add(?radius:Dynamic, ?view_align:Dynamic, ?enter_editmode:Dynamic, ?location:Dynamic, ?rotation:Dynamic):Dynamic;
	static public function radius_set(?radius:Dynamic):Dynamic;
	static public function reveal(?select:Dynamic):Dynamic;
	static public function select_all(?action:Dynamic):Dynamic;
	static public function select_less():Dynamic;
	static public function select_linked():Dynamic;
	static public function select_linked_pick(?deselect:Dynamic):Dynamic;
	static public function select_more():Dynamic;
	static public function select_next():Dynamic;
	static public function select_nth(?nth:Dynamic, ?skip:Dynamic, ?offset:Dynamic):Dynamic;
	static public function select_previous():Dynamic;
	static public function select_random(?percent:Dynamic, ?seed:Dynamic, ?action:Dynamic):Dynamic;
	static public function select_row():Dynamic;
	static public function select_similar(?type:Dynamic, ?compare:Dynamic, ?threshold:Dynamic):Dynamic;
	static public function separate():Dynamic;
	static public function shade_flat():Dynamic;
	static public function shade_smooth():Dynamic;
	static public function shortest_path_pick():Dynamic;
	static public function smooth():Dynamic;
	static public function smooth_radius():Dynamic;
	static public function smooth_tilt():Dynamic;
	static public function smooth_weight():Dynamic;
	static public function spin(?center:Dynamic, ?axis:Dynamic):Dynamic;
	static public function spline_type_set(?type:Dynamic, ?use_handles:Dynamic):Dynamic;
	static public function spline_weight_set(?weight:Dynamic):Dynamic;
	static public function split():Dynamic;
	static public function subdivide(?number_cuts:Dynamic):Dynamic;
	static public function switch_direction():Dynamic;
	static public function tilt_clear():Dynamic;
	static public function vertex_add(?location:Dynamic):Dynamic;
}