/* This file is generated, do not edit! */
package bmesh.ops;
@:pythonImport("bmesh.ops") extern class Ops_Module {
	static public var __builtins__ : Dynamic;
	static public var __cached__ : Dynamic;
	static public var __doc__ : Dynamic;
	static public var __file__ : Dynamic;
	static public var __loader__ : Dynamic;
	static public var __name__ : Dynamic;
	static public var __package__ : Dynamic;
	static public var __spec__ : Dynamic;
	static public function automerge(bm:Dynamic, verts:Dynamic, dist:Dynamic):Dynamic;
	static public function average_vert_facedata(bm:Dynamic, verts:Dynamic):Dynamic;
	static public function beautify_fill(bm:Dynamic, faces:Dynamic, edges:Dynamic, use_restrict_tag:Dynamic, method:Dynamic):Dynamic;
	static public function bevel(bm:Dynamic, geom:Dynamic, offset:Dynamic, offset_type:Dynamic, segments:Dynamic, profile:Dynamic, vertex_only:Dynamic, clamp_overlap:Dynamic, material:Dynamic, loop_slide:Dynamic, mark_seam:Dynamic, mark_sharp:Dynamic, strength:Dynamic, hnmode:Dynamic):Dynamic;
	static public function bisect_edges(bm:Dynamic, edges:Dynamic, cuts:Dynamic, edge_percents:Dynamic):Dynamic;
	static public function bisect_plane(bm:Dynamic, geom:Dynamic, dist:Dynamic, plane_co:Dynamic, plane_no:Dynamic, use_snap_center:Dynamic, clear_outer:Dynamic, clear_inner:Dynamic):Dynamic;
	static public function bmesh_to_mesh(bm:Dynamic, mesh:Dynamic, object:Dynamic):Dynamic;
	static public function bridge_loops(bm:Dynamic, edges:Dynamic, use_pairs:Dynamic, use_cyclic:Dynamic, use_merge:Dynamic, merge_factor:Dynamic, twist_offset:Dynamic):Dynamic;
	static public function collapse(bm:Dynamic, edges:Dynamic, uvs:Dynamic):Dynamic;
	static public function collapse_uvs(bm:Dynamic, edges:Dynamic):Dynamic;
	static public function connect_vert_pair(bm:Dynamic, verts:Dynamic, verts_exclude:Dynamic, faces_exclude:Dynamic):Dynamic;
	static public function connect_verts(bm:Dynamic, verts:Dynamic, faces_exclude:Dynamic, check_degenerate:Dynamic):Dynamic;
	static public function connect_verts_concave(bm:Dynamic, faces:Dynamic):Dynamic;
	static public function connect_verts_nonplanar(bm:Dynamic, angle_limit:Dynamic, faces:Dynamic):Dynamic;
	static public function contextual_create(bm:Dynamic, geom:Dynamic, mat_nr:Dynamic, use_smooth:Dynamic):Dynamic;
	static public function convex_hull(bm:Dynamic, input:Dynamic, use_existing_faces:Dynamic):Dynamic;
	static public function create_circle(bm:Dynamic, cap_ends:Dynamic, cap_tris:Dynamic, segments:Dynamic, radius:Dynamic, matrix:Dynamic, calc_uvs:Dynamic):Dynamic;
	static public function create_cone(bm:Dynamic, cap_ends:Dynamic, cap_tris:Dynamic, segments:Dynamic, diameter1:Dynamic, diameter2:Dynamic, depth:Dynamic, matrix:Dynamic, calc_uvs:Dynamic):Dynamic;
	static public function create_cube(bm:Dynamic, size:Dynamic, matrix:Dynamic, calc_uvs:Dynamic):Dynamic;
	static public function create_grid(bm:Dynamic, x_segments:Dynamic, y_segments:Dynamic, size:Dynamic, matrix:Dynamic, calc_uvs:Dynamic):Dynamic;
	static public function create_icosphere(bm:Dynamic, subdivisions:Dynamic, diameter:Dynamic, matrix:Dynamic, calc_uvs:Dynamic):Dynamic;
	static public function create_monkey(bm:Dynamic, matrix:Dynamic, calc_uvs:Dynamic):Dynamic;
	static public function create_uvsphere(bm:Dynamic, u_segments:Dynamic, v_segments:Dynamic, diameter:Dynamic, matrix:Dynamic, calc_uvs:Dynamic):Dynamic;
	static public function create_vert(bm:Dynamic, co:Dynamic):Dynamic;
	static public function delete(bm:Dynamic, geom:Dynamic, context:Dynamic):Dynamic;
	static public function dissolve_degenerate(bm:Dynamic, dist:Dynamic, edges:Dynamic):Dynamic;
	static public function dissolve_edges(bm:Dynamic, edges:Dynamic, use_verts:Dynamic, use_face_split:Dynamic):Dynamic;
	static public function dissolve_faces(bm:Dynamic, faces:Dynamic, use_verts:Dynamic):Dynamic;
	static public function dissolve_limit(bm:Dynamic, angle_limit:Dynamic, use_dissolve_boundaries:Dynamic, verts:Dynamic, edges:Dynamic, delimit:Dynamic):Dynamic;
	static public function dissolve_verts(bm:Dynamic, verts:Dynamic, use_face_split:Dynamic, use_boundary_tear:Dynamic):Dynamic;
	static public function duplicate(bm:Dynamic, geom:Dynamic, dest:Dynamic, use_select_history:Dynamic):Dynamic;
	static public function edgeloop_fill(bm:Dynamic, edges:Dynamic, mat_nr:Dynamic, use_smooth:Dynamic):Dynamic;
	static public function edgenet_fill(bm:Dynamic, edges:Dynamic, mat_nr:Dynamic, use_smooth:Dynamic, sides:Dynamic):Dynamic;
	static public function edgenet_prepare(bm:Dynamic, edges:Dynamic):Dynamic;
	static public function extrude_discrete_faces(bm:Dynamic, faces:Dynamic, use_select_history:Dynamic):Dynamic;
	static public function extrude_edge_only(bm:Dynamic, edges:Dynamic, use_select_history:Dynamic):Dynamic;
	static public function extrude_face_region(bm:Dynamic, geom:Dynamic, edges_exclude:Dynamic, use_keep_orig:Dynamic, use_select_history:Dynamic):Dynamic;
	static public function extrude_vert_indiv(bm:Dynamic, verts:Dynamic, use_select_history:Dynamic):Dynamic;
	static public function face_attribute_fill(bm:Dynamic, faces:Dynamic, use_normals:Dynamic, use_data:Dynamic):Dynamic;
	static public function find_doubles(bm:Dynamic, verts:Dynamic, keep_verts:Dynamic, dist:Dynamic):Dynamic;
	static public function grid_fill(bm:Dynamic, edges:Dynamic, mat_nr:Dynamic, use_smooth:Dynamic, use_interp_simple:Dynamic):Dynamic;
	static public function holes_fill(bm:Dynamic, edges:Dynamic, sides:Dynamic):Dynamic;
	static public function inset_individual(bm:Dynamic, faces:Dynamic, thickness:Dynamic, depth:Dynamic, use_even_offset:Dynamic, use_interpolate:Dynamic, use_relative_offset:Dynamic):Dynamic;
	static public function inset_region(bm:Dynamic, faces:Dynamic, faces_exclude:Dynamic, use_boundary:Dynamic, use_even_offset:Dynamic, use_interpolate:Dynamic, use_relative_offset:Dynamic, use_edge_rail:Dynamic, thickness:Dynamic, depth:Dynamic, use_outset:Dynamic):Dynamic;
	static public function join_triangles(bm:Dynamic, faces:Dynamic, cmp_seam:Dynamic, cmp_sharp:Dynamic, cmp_uvs:Dynamic, cmp_vcols:Dynamic, cmp_materials:Dynamic, angle_face_threshold:Dynamic, angle_shape_threshold:Dynamic):Dynamic;
	static public function mesh_to_bmesh(bm:Dynamic, mesh:Dynamic, object:Dynamic, use_shapekey:Dynamic):Dynamic;
	static public function mirror(bm:Dynamic, geom:Dynamic, matrix:Dynamic, merge_dist:Dynamic, axis:Dynamic, mirror_u:Dynamic, mirror_v:Dynamic):Dynamic;
	static public function object_load_bmesh(bm:Dynamic, scene:Dynamic, object:Dynamic):Dynamic;
	static public function offset_edgeloops(bm:Dynamic, edges:Dynamic, use_cap_endpoint:Dynamic):Dynamic;
	static public function planar_faces(bm:Dynamic, faces:Dynamic, iterations:Dynamic, factor:Dynamic):Dynamic;
	static public function pointmerge(bm:Dynamic, verts:Dynamic, merge_co:Dynamic):Dynamic;
	static public function pointmerge_facedata(bm:Dynamic, verts:Dynamic, vert_snap:Dynamic):Dynamic;
	static public function poke(bm:Dynamic, faces:Dynamic, offset:Dynamic, center_mode:Dynamic, use_relative_offset:Dynamic):Dynamic;
	static public function recalc_face_normals(bm:Dynamic, faces:Dynamic):Dynamic;
	static public function region_extend(bm:Dynamic, geom:Dynamic, use_contract:Dynamic, use_faces:Dynamic, use_face_step:Dynamic):Dynamic;
	static public function remove_doubles(bm:Dynamic, verts:Dynamic, dist:Dynamic):Dynamic;
	static public function reverse_colors(bm:Dynamic, faces:Dynamic):Dynamic;
	static public function reverse_faces(bm:Dynamic, faces:Dynamic, flip_multires:Dynamic):Dynamic;
	static public function reverse_uvs(bm:Dynamic, faces:Dynamic):Dynamic;
	static public function rotate(bm:Dynamic, cent:Dynamic, matrix:Dynamic, verts:Dynamic, space:Dynamic):Dynamic;
	static public function rotate_colors(bm:Dynamic, faces:Dynamic, use_ccw:Dynamic):Dynamic;
	static public function rotate_edges(bm:Dynamic, edges:Dynamic, use_ccw:Dynamic):Dynamic;
	static public function rotate_uvs(bm:Dynamic, faces:Dynamic, use_ccw:Dynamic):Dynamic;
	static public function scale(bm:Dynamic, vec:Dynamic, space:Dynamic, verts:Dynamic):Dynamic;
	static public function similar_edges(bm:Dynamic, edges:Dynamic, type:Dynamic, thresh:Dynamic, compare:Dynamic):Dynamic;
	static public function similar_faces(bm:Dynamic, faces:Dynamic, type:Dynamic, thresh:Dynamic, compare:Dynamic):Dynamic;
	static public function similar_verts(bm:Dynamic, verts:Dynamic, type:Dynamic, thresh:Dynamic, compare:Dynamic):Dynamic;
	static public function smooth_laplacian_vert(bm:Dynamic, verts:Dynamic, lambda_factor:Dynamic, lambda_border:Dynamic, use_x:Dynamic, use_y:Dynamic, use_z:Dynamic, preserve_volume:Dynamic):Dynamic;
	static public function smooth_vert(bm:Dynamic, verts:Dynamic, factor:Dynamic, mirror_clip_x:Dynamic, mirror_clip_y:Dynamic, mirror_clip_z:Dynamic, clip_dist:Dynamic, use_axis_x:Dynamic, use_axis_y:Dynamic, use_axis_z:Dynamic):Dynamic;
	static public function solidify(bm:Dynamic, geom:Dynamic, thickness:Dynamic):Dynamic;
	static public function spin(bm:Dynamic, geom:Dynamic, cent:Dynamic, axis:Dynamic, dvec:Dynamic, angle:Dynamic, space:Dynamic, steps:Dynamic, use_duplicate:Dynamic):Dynamic;
	static public function split(bm:Dynamic, geom:Dynamic, dest:Dynamic, use_only_faces:Dynamic):Dynamic;
	static public function split_edges(bm:Dynamic, edges:Dynamic, verts:Dynamic, use_verts:Dynamic):Dynamic;
	static public function subdivide_edgering(bm:Dynamic, edges:Dynamic, interp_mode:Dynamic, smooth:Dynamic, cuts:Dynamic, profile_shape:Dynamic, profile_shape_factor:Dynamic):Dynamic;
	static public function subdivide_edges(bm:Dynamic, edges:Dynamic, smooth:Dynamic, smooth_falloff:Dynamic, fractal:Dynamic, along_normal:Dynamic, cuts:Dynamic, seed:Dynamic, custom_patterns:Dynamic, edge_percents:Dynamic, quad_corner_type:Dynamic, use_grid_fill:Dynamic, use_single_edge:Dynamic, use_only_quads:Dynamic, use_sphere:Dynamic, use_smooth_even:Dynamic):Dynamic;
	static public function symmetrize(bm:Dynamic, input:Dynamic, direction:Dynamic, dist:Dynamic):Dynamic;
	static public function transform(bm:Dynamic, matrix:Dynamic, space:Dynamic, verts:Dynamic):Dynamic;
	static public function translate(bm:Dynamic, vec:Dynamic, space:Dynamic, verts:Dynamic):Dynamic;
	static public function triangle_fill(bm:Dynamic, use_beauty:Dynamic, use_dissolve:Dynamic, edges:Dynamic, normal:Dynamic):Dynamic;
	static public function triangulate(bm:Dynamic, faces:Dynamic, quad_method:Dynamic, ngon_method:Dynamic):Dynamic;
	static public function unsubdivide(bm:Dynamic, verts:Dynamic, iterations:Dynamic):Dynamic;
	static public function weld_verts(bm:Dynamic, targetmap:Dynamic):Dynamic;
	static public function wireframe(bm:Dynamic, faces:Dynamic, thickness:Dynamic, offset:Dynamic, use_replace:Dynamic, use_boundary:Dynamic, use_even_offset:Dynamic, use_crease:Dynamic, crease_weight:Dynamic, use_relative_offset:Dynamic, material_offset:Dynamic):Dynamic;
}