/* This file is generated, do not edit! */
package bpy.ops.gpencil;
@:pythonImport("bpy.ops.gpencil") extern class Gpencil_Module {
	static public var __builtins__ : Dynamic;
	static public var __cached__ : Dynamic;
	static public var __doc__ : Dynamic;
	static public var __file__ : Dynamic;
	static public var __loader__ : Dynamic;
	static public var __name__ : Dynamic;
	static public var __package__ : Dynamic;
	static public var __spec__ : Dynamic;
	static public function active_frame_delete():Dynamic;
	static public function active_frames_delete_all():Dynamic;
	static public function annotate(?mode:Dynamic, ?stroke:Dynamic, ?wait_for_input:Dynamic):Dynamic;
	static public function blank_frame_add(?all_layers:Dynamic):Dynamic;
	static public function brush_paint(?mode:Dynamic, ?stroke:Dynamic, ?wait_for_input:Dynamic, ?keep_brush:Dynamic):Dynamic;
	static public function brush_presets_create():Dynamic;
	static public function brush_select(?index:Dynamic):Dynamic;
	static public function color_hide(?unselected:Dynamic):Dynamic;
	static public function color_isolate(?affect_visibility:Dynamic):Dynamic;
	static public function color_lock_all():Dynamic;
	static public function color_reveal():Dynamic;
	static public function color_select():Dynamic;
	static public function color_unlock_all():Dynamic;
	static public function convert(?type:Dynamic, ?use_normalize_weights:Dynamic, ?radius_multiplier:Dynamic, ?use_link_strokes:Dynamic, ?timing_mode:Dynamic, ?frame_range:Dynamic, ?start_frame:Dynamic, ?use_realtime:Dynamic, ?end_frame:Dynamic, ?gap_duration:Dynamic, ?gap_randomness:Dynamic, ?seed:Dynamic, ?use_timing_data:Dynamic):Dynamic;
	static public function convert_old_files():Dynamic;
	static public function copy():Dynamic;
	static public function data_add():Dynamic;
	static public function data_unlink():Dynamic;
	static public function delete(?type:Dynamic):Dynamic;
	static public function dissolve(?type:Dynamic):Dynamic;
	static public function draw(?mode:Dynamic, ?stroke:Dynamic, ?wait_for_input:Dynamic, ?disable_straight:Dynamic, ?disable_fill:Dynamic):Dynamic;
	static public function duplicate():Dynamic;
	static public function duplicate_move(?GPENCIL_OT_duplicate:Dynamic, ?TRANSFORM_OT_translate:Dynamic):Dynamic;
	static public function editmode_toggle(?back:Dynamic):Dynamic;
	static public function fill(?on_back:Dynamic):Dynamic;
	static public function frame_clean_fill(?mode:Dynamic):Dynamic;
	static public function frame_clean_loose(?limit:Dynamic):Dynamic;
	static public function frame_duplicate(?mode:Dynamic):Dynamic;
	static public function generate_weights(?mode:Dynamic, ?armature:Dynamic, ?ratio:Dynamic, ?decay:Dynamic):Dynamic;
	static public function hide(?unselected:Dynamic):Dynamic;
	static public function interpolate(?shift:Dynamic):Dynamic;
	static public function interpolate_reverse():Dynamic;
	static public function interpolate_sequence():Dynamic;
	static public function layer_add():Dynamic;
	static public function layer_change(?layer:Dynamic):Dynamic;
	static public function layer_duplicate():Dynamic;
	static public function layer_duplicate_object(?object:Dynamic, ?mode:Dynamic):Dynamic;
	static public function layer_isolate(?affect_visibility:Dynamic):Dynamic;
	static public function layer_merge():Dynamic;
	static public function layer_move(?type:Dynamic):Dynamic;
	static public function layer_remove():Dynamic;
	static public function lock_all():Dynamic;
	static public function lock_layer():Dynamic;
	static public function move_to_layer(?layer:Dynamic):Dynamic;
	static public function paintmode_toggle(?back:Dynamic):Dynamic;
	static public function paste(?type:Dynamic):Dynamic;
	static public function primitive(?edges:Dynamic, ?type:Dynamic):Dynamic;
	static public function reproject(?type:Dynamic):Dynamic;
	static public function reveal(?select:Dynamic):Dynamic;
	static public function sculpt_select(?index:Dynamic):Dynamic;
	static public function sculptmode_toggle(?back:Dynamic):Dynamic;
	static public function select(?extend:Dynamic, ?deselect:Dynamic, ?toggle:Dynamic, ?entire_strokes:Dynamic, ?location:Dynamic):Dynamic;
	static public function select_all(?action:Dynamic):Dynamic;
	static public function select_alternate(?unselect_ends:Dynamic):Dynamic;
	static public function select_border(?xmin:Dynamic, ?xmax:Dynamic, ?ymin:Dynamic, ?ymax:Dynamic, ?deselect:Dynamic, ?extend:Dynamic):Dynamic;
	static public function select_circle(?x:Dynamic, ?y:Dynamic, ?radius:Dynamic, ?deselect:Dynamic):Dynamic;
	static public function select_first(?only_selected_strokes:Dynamic, ?extend:Dynamic):Dynamic;
	static public function select_grouped(?type:Dynamic):Dynamic;
	static public function select_lasso(?path:Dynamic, ?deselect:Dynamic, ?extend:Dynamic):Dynamic;
	static public function select_last(?only_selected_strokes:Dynamic, ?extend:Dynamic):Dynamic;
	static public function select_less():Dynamic;
	static public function select_linked():Dynamic;
	static public function select_more():Dynamic;
	static public function selection_opacity_toggle():Dynamic;
	static public function snap_cursor_to_selected():Dynamic;
	static public function snap_to_cursor(?use_offset:Dynamic):Dynamic;
	static public function snap_to_grid():Dynamic;
	static public function stroke_apply_thickness():Dynamic;
	static public function stroke_arrange(?direction:Dynamic):Dynamic;
	static public function stroke_change_color(?material:Dynamic):Dynamic;
	static public function stroke_cyclical_set(?type:Dynamic):Dynamic;
	static public function stroke_flip():Dynamic;
	static public function stroke_join(?type:Dynamic, ?leave_gaps:Dynamic):Dynamic;
	static public function stroke_lock_color():Dynamic;
	static public function stroke_separate(?mode:Dynamic):Dynamic;
	static public function stroke_simplify(?factor:Dynamic):Dynamic;
	static public function stroke_simplify_fixed(?step:Dynamic):Dynamic;
	static public function stroke_split():Dynamic;
	static public function stroke_subdivide(?number_cuts:Dynamic):Dynamic;
	static public function unlock_all():Dynamic;
	static public function vertex_group_assign():Dynamic;
	static public function vertex_group_deselect():Dynamic;
	static public function vertex_group_invert():Dynamic;
	static public function vertex_group_remove_from():Dynamic;
	static public function vertex_group_select():Dynamic;
	static public function vertex_group_smooth(?factor:Dynamic, ?repeat:Dynamic):Dynamic;
	static public function weightmode_toggle(?back:Dynamic):Dynamic;
}