/* This file is generated, do not edit! */
package bpy.ops.graph;
@:pythonImport("bpy.ops.graph") extern class Graph_Module {
	static public var __builtins__ : Dynamic;
	static public var __cached__ : Dynamic;
	static public var __doc__ : Dynamic;
	static public var __file__ : Dynamic;
	static public var __loader__ : Dynamic;
	static public var __name__ : Dynamic;
	static public var __package__ : Dynamic;
	static public var __spec__ : Dynamic;
	static public function bake():Dynamic;
	static public function clean(?threshold:Dynamic, ?channels:Dynamic):Dynamic;
	static public function click_insert(?frame:Dynamic, ?value:Dynamic, ?extend:Dynamic):Dynamic;
	static public function clickselect(?extend:Dynamic, ?column:Dynamic, ?curves:Dynamic):Dynamic;
	static public function copy():Dynamic;
	static public function cursor_set(?frame:Dynamic, ?value:Dynamic):Dynamic;
	static public function delete():Dynamic;
	static public function driver_delete_invalid():Dynamic;
	static public function driver_variables_copy():Dynamic;
	static public function driver_variables_paste(?replace:Dynamic):Dynamic;
	static public function duplicate(?mode:Dynamic):Dynamic;
	static public function duplicate_move(?GRAPH_OT_duplicate:Dynamic, ?TRANSFORM_OT_transform:Dynamic):Dynamic;
	static public function easing_type(?type:Dynamic):Dynamic;
	static public function euler_filter():Dynamic;
	static public function extrapolation_type(?type:Dynamic):Dynamic;
	static public function fmodifier_add(?type:Dynamic, ?only_active:Dynamic):Dynamic;
	static public function fmodifier_copy():Dynamic;
	static public function fmodifier_paste(?only_active:Dynamic, ?replace:Dynamic):Dynamic;
	static public function frame_jump():Dynamic;
	static public function ghost_curves_clear():Dynamic;
	static public function ghost_curves_create():Dynamic;
	static public function handle_type(?type:Dynamic):Dynamic;
	static public function hide(?unselected:Dynamic):Dynamic;
	static public function interpolation_type(?type:Dynamic):Dynamic;
	static public function keyframe_insert(?type:Dynamic):Dynamic;
	static public function mirror(?type:Dynamic):Dynamic;
	static public function paste(?offset:Dynamic, ?merge:Dynamic, ?flipped:Dynamic):Dynamic;
	static public function previewrange_set():Dynamic;
	static public function properties():Dynamic;
	static public function reveal(?select:Dynamic):Dynamic;
	static public function sample():Dynamic;
	static public function select_all(?action:Dynamic):Dynamic;
	static public function select_border(?xmin:Dynamic, ?xmax:Dynamic, ?ymin:Dynamic, ?ymax:Dynamic, ?deselect:Dynamic, ?extend:Dynamic, ?axis_range:Dynamic, ?include_handles:Dynamic):Dynamic;
	static public function select_circle(?x:Dynamic, ?y:Dynamic, ?radius:Dynamic, ?deselect:Dynamic):Dynamic;
	static public function select_column(?mode:Dynamic):Dynamic;
	static public function select_lasso(?path:Dynamic, ?deselect:Dynamic, ?extend:Dynamic):Dynamic;
	static public function select_leftright(?mode:Dynamic, ?extend:Dynamic):Dynamic;
	static public function select_less():Dynamic;
	static public function select_linked():Dynamic;
	static public function select_more():Dynamic;
	static public function smooth():Dynamic;
	static public function snap(?type:Dynamic):Dynamic;
	static public function sound_bake(?filepath:Dynamic, ?filter_blender:Dynamic, ?filter_backup:Dynamic, ?filter_image:Dynamic, ?filter_movie:Dynamic, ?filter_python:Dynamic, ?filter_font:Dynamic, ?filter_sound:Dynamic, ?filter_text:Dynamic, ?filter_btx:Dynamic, ?filter_collada:Dynamic, ?filter_alembic:Dynamic, ?filter_folder:Dynamic, ?filter_blenlib:Dynamic, ?filemode:Dynamic, ?show_multiview:Dynamic, ?use_multiview:Dynamic, ?display_type:Dynamic, ?sort_method:Dynamic, ?low:Dynamic, ?high:Dynamic, ?attack:Dynamic, ?release:Dynamic, ?threshold:Dynamic, ?use_accumulate:Dynamic, ?use_additive:Dynamic, ?use_square:Dynamic, ?sthreshold:Dynamic):Dynamic;
	static public function view_all(?include_handles:Dynamic):Dynamic;
	static public function view_frame():Dynamic;
	static public function view_selected(?include_handles:Dynamic):Dynamic;
}