/* This file is generated, do not edit! */
package bpy.ops.outliner;
@:pythonImport("bpy.ops.outliner") extern class Outliner_Module {
	static public var __builtins__ : Dynamic;
	static public var __cached__ : Dynamic;
	static public var __doc__ : Dynamic;
	static public var __file__ : Dynamic;
	static public var __loader__ : Dynamic;
	static public var __name__ : Dynamic;
	static public var __package__ : Dynamic;
	static public var __spec__ : Dynamic;
	static public function action_set(?action:Dynamic):Dynamic;
	static public function animdata_operation(?type:Dynamic):Dynamic;
	static public function collection_delete(?hierarchy:Dynamic):Dynamic;
	static public function collection_drop():Dynamic;
	static public function collection_duplicate():Dynamic;
	static public function collection_exclude_clear():Dynamic;
	static public function collection_exclude_set():Dynamic;
	static public function collection_holdout_clear():Dynamic;
	static public function collection_holdout_set():Dynamic;
	static public function collection_indirect_only_clear():Dynamic;
	static public function collection_indirect_only_set():Dynamic;
	static public function collection_instance():Dynamic;
	static public function collection_link():Dynamic;
	static public function collection_new(?nested:Dynamic):Dynamic;
	static public function collection_objects_deselect():Dynamic;
	static public function collection_objects_select():Dynamic;
	static public function constraint_operation(?type:Dynamic):Dynamic;
	static public function data_operation(?type:Dynamic):Dynamic;
	static public function drivers_add_selected():Dynamic;
	static public function drivers_delete_selected():Dynamic;
	static public function expanded_toggle():Dynamic;
	static public function highlight_update():Dynamic;
	static public function id_delete():Dynamic;
	static public function id_operation(?type:Dynamic):Dynamic;
	static public function id_remap(?id_type:Dynamic, ?old_id:Dynamic, ?new_id:Dynamic):Dynamic;
	static public function item_activate(?extend:Dynamic, ?recursive:Dynamic):Dynamic;
	static public function item_drag_drop():Dynamic;
	static public function item_openclose(?all:Dynamic):Dynamic;
	static public function item_rename():Dynamic;
	static public function keyingset_add_selected():Dynamic;
	static public function keyingset_remove_selected():Dynamic;
	static public function lib_operation(?type:Dynamic):Dynamic;
	static public function lib_relocate():Dynamic;
	static public function material_drop():Dynamic;
	static public function modifier_operation(?type:Dynamic):Dynamic;
	static public function object_operation(?type:Dynamic):Dynamic;
	static public function operation():Dynamic;
	static public function orphans_purge():Dynamic;
	static public function parent_clear():Dynamic;
	static public function parent_drop(?child:Dynamic, ?parent:Dynamic, ?type:Dynamic):Dynamic;
	static public function scene_drop():Dynamic;
	static public function scene_operation(?type:Dynamic):Dynamic;
	static public function scroll_page(?up:Dynamic):Dynamic;
	static public function select_all(?action:Dynamic):Dynamic;
	static public function select_border(?xmin:Dynamic, ?xmax:Dynamic, ?ymin:Dynamic, ?ymax:Dynamic, ?deselect:Dynamic):Dynamic;
	static public function show_active():Dynamic;
	static public function show_hierarchy():Dynamic;
	static public function show_one_level(?open:Dynamic):Dynamic;
}