/* This file is generated, do not edit! */
package bpy.ops.text;
@:pythonImport("bpy.ops.text") extern class Text_Module {
	static public var __builtins__ : Dynamic;
	static public var __cached__ : Dynamic;
	static public var __doc__ : Dynamic;
	static public var __file__ : Dynamic;
	static public var __loader__ : Dynamic;
	static public var __name__ : Dynamic;
	static public var __package__ : Dynamic;
	static public var __spec__ : Dynamic;
	static public function autocomplete():Dynamic;
	static public function comment():Dynamic;
	static public function convert_whitespace(?type:Dynamic):Dynamic;
	static public function copy():Dynamic;
	static public function cursor_set(?x:Dynamic, ?y:Dynamic):Dynamic;
	static public function cut():Dynamic;
	static public function delete(?type:Dynamic):Dynamic;
	static public function duplicate_line():Dynamic;
	static public function find():Dynamic;
	static public function find_set_selected():Dynamic;
	static public function indent():Dynamic;
	static public function insert(?text:Dynamic):Dynamic;
	static public function jump(?line:Dynamic):Dynamic;
	static public function line_break():Dynamic;
	static public function line_number():Dynamic;
	static public function make_internal():Dynamic;
	static public function move(?type:Dynamic):Dynamic;
	static public function move_lines(?direction:Dynamic):Dynamic;
	static public function move_select(?type:Dynamic):Dynamic;
	@:native("new")
	static public function _new():Dynamic;
	static public function open(?filepath:Dynamic, ?filter_blender:Dynamic, ?filter_backup:Dynamic, ?filter_image:Dynamic, ?filter_movie:Dynamic, ?filter_python:Dynamic, ?filter_font:Dynamic, ?filter_sound:Dynamic, ?filter_text:Dynamic, ?filter_btx:Dynamic, ?filter_collada:Dynamic, ?filter_alembic:Dynamic, ?filter_folder:Dynamic, ?filter_blenlib:Dynamic, ?filemode:Dynamic, ?display_type:Dynamic, ?sort_method:Dynamic, ?internal:Dynamic):Dynamic;
	static public function overwrite_toggle():Dynamic;
	static public function paste(?selection:Dynamic):Dynamic;
	static public function properties():Dynamic;
	static public function refresh_pyconstraints():Dynamic;
	static public function reload():Dynamic;
	static public function replace():Dynamic;
	static public function replace_set_selected():Dynamic;
	static public function resolve_conflict(?resolution:Dynamic):Dynamic;
	static public function run_script():Dynamic;
	static public function save():Dynamic;
	static public function save_as(?filepath:Dynamic, ?check_existing:Dynamic, ?filter_blender:Dynamic, ?filter_backup:Dynamic, ?filter_image:Dynamic, ?filter_movie:Dynamic, ?filter_python:Dynamic, ?filter_font:Dynamic, ?filter_sound:Dynamic, ?filter_text:Dynamic, ?filter_btx:Dynamic, ?filter_collada:Dynamic, ?filter_alembic:Dynamic, ?filter_folder:Dynamic, ?filter_blenlib:Dynamic, ?filemode:Dynamic, ?display_type:Dynamic, ?sort_method:Dynamic):Dynamic;
	static public function scroll(?lines:Dynamic):Dynamic;
	static public function scroll_bar(?lines:Dynamic):Dynamic;
	static public function select_all():Dynamic;
	static public function select_line():Dynamic;
	static public function select_word():Dynamic;
	static public function selection_set(?select:Dynamic):Dynamic;
	static public function start_find():Dynamic;
	static public function to_3d_object(?split_lines:Dynamic):Dynamic;
	static public function uncomment():Dynamic;
	static public function unindent():Dynamic;
	static public function unlink():Dynamic;
}