/* This file is generated, do not edit! */
package bpy.ops.transform;
@:pythonImport("bpy.ops.transform") extern class Transform_Module {
	static public var __builtins__ : Dynamic;
	static public var __cached__ : Dynamic;
	static public var __doc__ : Dynamic;
	static public var __file__ : Dynamic;
	static public var __loader__ : Dynamic;
	static public var __name__ : Dynamic;
	static public var __package__ : Dynamic;
	static public var __spec__ : Dynamic;
	static public function bend(?value:Dynamic, ?mirror:Dynamic, ?proportional:Dynamic, ?proportional_edit_falloff:Dynamic, ?proportional_size:Dynamic, ?snap:Dynamic, ?snap_target:Dynamic, ?snap_point:Dynamic, ?snap_align:Dynamic, ?snap_normal:Dynamic, ?gpencil_strokes:Dynamic, ?center_override:Dynamic, ?release_confirm:Dynamic, ?use_accurate:Dynamic):Dynamic;
	static public function create_orientation(?name:Dynamic, ?use_view:Dynamic, ?use:Dynamic, ?overwrite:Dynamic):Dynamic;
	static public function delete_orientation():Dynamic;
	static public function edge_bevelweight(?value:Dynamic, ?snap:Dynamic, ?snap_target:Dynamic, ?snap_point:Dynamic, ?snap_align:Dynamic, ?snap_normal:Dynamic, ?release_confirm:Dynamic, ?use_accurate:Dynamic):Dynamic;
	static public function edge_crease(?value:Dynamic, ?snap:Dynamic, ?snap_target:Dynamic, ?snap_point:Dynamic, ?snap_align:Dynamic, ?snap_normal:Dynamic, ?release_confirm:Dynamic, ?use_accurate:Dynamic):Dynamic;
	static public function edge_slide(?value:Dynamic, ?single_side:Dynamic, ?use_even:Dynamic, ?flipped:Dynamic, ?use_clamp:Dynamic, ?mirror:Dynamic, ?snap:Dynamic, ?snap_target:Dynamic, ?snap_point:Dynamic, ?snap_align:Dynamic, ?snap_normal:Dynamic, ?correct_uv:Dynamic, ?release_confirm:Dynamic, ?use_accurate:Dynamic):Dynamic;
	static public function mirror(?constraint_axis:Dynamic, ?constraint_orientation:Dynamic, ?proportional:Dynamic, ?proportional_edit_falloff:Dynamic, ?proportional_size:Dynamic, ?gpencil_strokes:Dynamic, ?center_override:Dynamic, ?release_confirm:Dynamic, ?use_accurate:Dynamic):Dynamic;
	static public function push_pull(?value:Dynamic, ?mirror:Dynamic, ?proportional:Dynamic, ?proportional_edit_falloff:Dynamic, ?proportional_size:Dynamic, ?snap:Dynamic, ?snap_target:Dynamic, ?snap_point:Dynamic, ?snap_align:Dynamic, ?snap_normal:Dynamic, ?center_override:Dynamic, ?release_confirm:Dynamic, ?use_accurate:Dynamic):Dynamic;
	static public function resize(?value:Dynamic, ?constraint_axis:Dynamic, ?constraint_orientation:Dynamic, ?mirror:Dynamic, ?proportional:Dynamic, ?proportional_edit_falloff:Dynamic, ?proportional_size:Dynamic, ?snap:Dynamic, ?snap_target:Dynamic, ?snap_point:Dynamic, ?snap_align:Dynamic, ?snap_normal:Dynamic, ?gpencil_strokes:Dynamic, ?texture_space:Dynamic, ?remove_on_cancel:Dynamic, ?center_override:Dynamic, ?release_confirm:Dynamic, ?use_accurate:Dynamic):Dynamic;
	static public function rotate(?value:Dynamic, ?axis:Dynamic, ?constraint_axis:Dynamic, ?constraint_orientation:Dynamic, ?mirror:Dynamic, ?proportional:Dynamic, ?proportional_edit_falloff:Dynamic, ?proportional_size:Dynamic, ?snap:Dynamic, ?snap_target:Dynamic, ?snap_point:Dynamic, ?snap_align:Dynamic, ?snap_normal:Dynamic, ?gpencil_strokes:Dynamic, ?center_override:Dynamic, ?release_confirm:Dynamic, ?use_accurate:Dynamic):Dynamic;
	static public function rotate_normal(?value:Dynamic, ?axis:Dynamic, ?constraint_axis:Dynamic, ?constraint_orientation:Dynamic, ?mirror:Dynamic, ?release_confirm:Dynamic, ?use_accurate:Dynamic):Dynamic;
	static public function select_orientation(?orientation:Dynamic):Dynamic;
	static public function seq_slide(?value:Dynamic, ?snap:Dynamic, ?snap_target:Dynamic, ?snap_point:Dynamic, ?snap_align:Dynamic, ?snap_normal:Dynamic, ?release_confirm:Dynamic, ?use_accurate:Dynamic):Dynamic;
	static public function shear(?value:Dynamic, ?mirror:Dynamic, ?proportional:Dynamic, ?proportional_edit_falloff:Dynamic, ?proportional_size:Dynamic, ?snap:Dynamic, ?snap_target:Dynamic, ?snap_point:Dynamic, ?snap_align:Dynamic, ?snap_normal:Dynamic, ?gpencil_strokes:Dynamic, ?release_confirm:Dynamic, ?use_accurate:Dynamic):Dynamic;
	static public function shrink_fatten(?value:Dynamic, ?use_even_offset:Dynamic, ?mirror:Dynamic, ?proportional:Dynamic, ?proportional_edit_falloff:Dynamic, ?proportional_size:Dynamic, ?snap:Dynamic, ?snap_target:Dynamic, ?snap_point:Dynamic, ?snap_align:Dynamic, ?snap_normal:Dynamic, ?release_confirm:Dynamic, ?use_accurate:Dynamic):Dynamic;
	static public function skin_resize(?value:Dynamic, ?constraint_axis:Dynamic, ?constraint_orientation:Dynamic, ?mirror:Dynamic, ?proportional:Dynamic, ?proportional_edit_falloff:Dynamic, ?proportional_size:Dynamic, ?snap:Dynamic, ?snap_target:Dynamic, ?snap_point:Dynamic, ?snap_align:Dynamic, ?snap_normal:Dynamic, ?release_confirm:Dynamic, ?use_accurate:Dynamic):Dynamic;
	static public function tilt(?value:Dynamic, ?mirror:Dynamic, ?proportional:Dynamic, ?proportional_edit_falloff:Dynamic, ?proportional_size:Dynamic, ?snap:Dynamic, ?snap_target:Dynamic, ?snap_point:Dynamic, ?snap_align:Dynamic, ?snap_normal:Dynamic, ?release_confirm:Dynamic, ?use_accurate:Dynamic):Dynamic;
	static public function tosphere(?value:Dynamic, ?mirror:Dynamic, ?proportional:Dynamic, ?proportional_edit_falloff:Dynamic, ?proportional_size:Dynamic, ?snap:Dynamic, ?snap_target:Dynamic, ?snap_point:Dynamic, ?snap_align:Dynamic, ?snap_normal:Dynamic, ?gpencil_strokes:Dynamic, ?center_override:Dynamic, ?release_confirm:Dynamic, ?use_accurate:Dynamic):Dynamic;
	static public function trackball(?value:Dynamic, ?mirror:Dynamic, ?proportional:Dynamic, ?proportional_edit_falloff:Dynamic, ?proportional_size:Dynamic, ?snap:Dynamic, ?snap_target:Dynamic, ?snap_point:Dynamic, ?snap_align:Dynamic, ?snap_normal:Dynamic, ?gpencil_strokes:Dynamic, ?center_override:Dynamic, ?release_confirm:Dynamic, ?use_accurate:Dynamic):Dynamic;
	static public function transform(?mode:Dynamic, ?value:Dynamic, ?axis:Dynamic, ?constraint_axis:Dynamic, ?constraint_orientation:Dynamic, ?mirror:Dynamic, ?proportional:Dynamic, ?proportional_edit_falloff:Dynamic, ?proportional_size:Dynamic, ?snap:Dynamic, ?snap_target:Dynamic, ?snap_point:Dynamic, ?snap_align:Dynamic, ?snap_normal:Dynamic, ?gpencil_strokes:Dynamic, ?center_override:Dynamic, ?release_confirm:Dynamic, ?use_accurate:Dynamic):Dynamic;
	static public function translate(?value:Dynamic, ?constraint_axis:Dynamic, ?constraint_orientation:Dynamic, ?mirror:Dynamic, ?proportional:Dynamic, ?proportional_edit_falloff:Dynamic, ?proportional_size:Dynamic, ?snap:Dynamic, ?snap_target:Dynamic, ?snap_point:Dynamic, ?snap_align:Dynamic, ?snap_normal:Dynamic, ?gpencil_strokes:Dynamic, ?cursor_transform:Dynamic, ?texture_space:Dynamic, ?remove_on_cancel:Dynamic, ?release_confirm:Dynamic, ?use_accurate:Dynamic):Dynamic;
	static public function vert_slide(?value:Dynamic, ?use_even:Dynamic, ?flipped:Dynamic, ?use_clamp:Dynamic, ?mirror:Dynamic, ?snap:Dynamic, ?snap_target:Dynamic, ?snap_point:Dynamic, ?snap_align:Dynamic, ?snap_normal:Dynamic, ?correct_uv:Dynamic, ?release_confirm:Dynamic, ?use_accurate:Dynamic):Dynamic;
	static public function vertex_random(?offset:Dynamic, ?uniform:Dynamic, ?normal:Dynamic, ?seed:Dynamic):Dynamic;
	static public function vertex_warp(?warp_angle:Dynamic, ?offset_angle:Dynamic, ?min:Dynamic, ?max:Dynamic, ?viewmat:Dynamic, ?center:Dynamic):Dynamic;
}