/* This file is generated, do not edit! */
package bpy.ops.wm;
@:pythonImport("bpy.ops.wm") extern class Wm_Module {
	static public var __builtins__ : Dynamic;
	static public var __cached__ : Dynamic;
	static public var __doc__ : Dynamic;
	static public var __file__ : Dynamic;
	static public var __loader__ : Dynamic;
	static public var __name__ : Dynamic;
	static public var __package__ : Dynamic;
	static public var __spec__ : Dynamic;
	static public function addon_disable(?module:Dynamic):Dynamic;
	static public function addon_enable(?module:Dynamic):Dynamic;
	static public function addon_expand(?module:Dynamic):Dynamic;
	static public function addon_install(?overwrite:Dynamic, ?target:Dynamic, ?filepath:Dynamic, ?filter_folder:Dynamic, ?filter_python:Dynamic, ?filter_glob:Dynamic):Dynamic;
	static public function addon_refresh():Dynamic;
	static public function addon_remove(?module:Dynamic):Dynamic;
	static public function addon_userpref_show(?module:Dynamic):Dynamic;
	static public function alembic_export(?filepath:Dynamic, ?check_existing:Dynamic, ?filter_blender:Dynamic, ?filter_backup:Dynamic, ?filter_image:Dynamic, ?filter_movie:Dynamic, ?filter_python:Dynamic, ?filter_font:Dynamic, ?filter_sound:Dynamic, ?filter_text:Dynamic, ?filter_btx:Dynamic, ?filter_collada:Dynamic, ?filter_alembic:Dynamic, ?filter_folder:Dynamic, ?filter_blenlib:Dynamic, ?filemode:Dynamic, ?display_type:Dynamic, ?sort_method:Dynamic, ?start:Dynamic, ?end:Dynamic, ?xsamples:Dynamic, ?gsamples:Dynamic, ?sh_open:Dynamic, ?sh_close:Dynamic, ?selected:Dynamic, ?renderable_only:Dynamic, ?visible_layers_only:Dynamic, ?flatten:Dynamic, ?uvs:Dynamic, ?packuv:Dynamic, ?normals:Dynamic, ?vcolors:Dynamic, ?face_sets:Dynamic, ?subdiv_schema:Dynamic, ?apply_subdiv:Dynamic, ?compression_type:Dynamic, ?global_scale:Dynamic, ?triangulate:Dynamic, ?quad_method:Dynamic, ?ngon_method:Dynamic, ?export_hair:Dynamic, ?export_particles:Dynamic, ?as_background_job:Dynamic, ?init_scene_frame_range:Dynamic):Dynamic;
	static public function alembic_import(?filepath:Dynamic, ?check_existing:Dynamic, ?filter_blender:Dynamic, ?filter_backup:Dynamic, ?filter_image:Dynamic, ?filter_movie:Dynamic, ?filter_python:Dynamic, ?filter_font:Dynamic, ?filter_sound:Dynamic, ?filter_text:Dynamic, ?filter_btx:Dynamic, ?filter_collada:Dynamic, ?filter_alembic:Dynamic, ?filter_folder:Dynamic, ?filter_blenlib:Dynamic, ?filemode:Dynamic, ?display_type:Dynamic, ?sort_method:Dynamic, ?scale:Dynamic, ?set_frame_range:Dynamic, ?validate_meshes:Dynamic, ?is_sequence:Dynamic, ?as_background_job:Dynamic):Dynamic;
	static public function app_template_install(?overwrite:Dynamic, ?filepath:Dynamic, ?filter_folder:Dynamic, ?filter_glob:Dynamic):Dynamic;
	static public function appconfig_activate(?filepath:Dynamic):Dynamic;
	static public function appconfig_default():Dynamic;
	static public function append(?filepath:Dynamic, ?directory:Dynamic, ?filename:Dynamic, ?files:Dynamic, ?filter_blender:Dynamic, ?filter_backup:Dynamic, ?filter_image:Dynamic, ?filter_movie:Dynamic, ?filter_python:Dynamic, ?filter_font:Dynamic, ?filter_sound:Dynamic, ?filter_text:Dynamic, ?filter_btx:Dynamic, ?filter_collada:Dynamic, ?filter_alembic:Dynamic, ?filter_folder:Dynamic, ?filter_blenlib:Dynamic, ?filemode:Dynamic, ?display_type:Dynamic, ?sort_method:Dynamic, ?link:Dynamic, ?autoselect:Dynamic, ?active_collection:Dynamic, ?instance_collections:Dynamic, ?set_fake:Dynamic, ?use_recursive:Dynamic):Dynamic;
	static public function blend_strings_utf8_validate():Dynamic;
	static public function call_menu(?name:Dynamic):Dynamic;
	static public function call_menu_pie(?name:Dynamic):Dynamic;
	static public function call_panel(?name:Dynamic, ?keep_open:Dynamic):Dynamic;
	static public function collada_export(?filepath:Dynamic, ?check_existing:Dynamic, ?filter_blender:Dynamic, ?filter_backup:Dynamic, ?filter_image:Dynamic, ?filter_movie:Dynamic, ?filter_python:Dynamic, ?filter_font:Dynamic, ?filter_sound:Dynamic, ?filter_text:Dynamic, ?filter_btx:Dynamic, ?filter_collada:Dynamic, ?filter_alembic:Dynamic, ?filter_folder:Dynamic, ?filter_blenlib:Dynamic, ?filemode:Dynamic, ?display_type:Dynamic, ?sort_method:Dynamic, ?apply_modifiers:Dynamic, ?export_mesh_type:Dynamic, ?export_mesh_type_selection:Dynamic, ?selected:Dynamic, ?include_children:Dynamic, ?include_armatures:Dynamic, ?include_shapekeys:Dynamic, ?deform_bones_only:Dynamic, ?include_animations:Dynamic, ?sample_animations:Dynamic, ?sampling_rate:Dynamic, ?active_uv_only:Dynamic, ?include_material_textures:Dynamic, ?use_texture_copies:Dynamic, ?triangulate:Dynamic, ?use_object_instantiation:Dynamic, ?use_blender_profile:Dynamic, ?sort_by_name:Dynamic, ?export_transformation_type:Dynamic, ?export_transformation_type_selection:Dynamic, ?open_sim:Dynamic, ?limit_precision:Dynamic, ?keep_bind_info:Dynamic):Dynamic;
	static public function collada_import(?filepath:Dynamic, ?filter_blender:Dynamic, ?filter_backup:Dynamic, ?filter_image:Dynamic, ?filter_movie:Dynamic, ?filter_python:Dynamic, ?filter_font:Dynamic, ?filter_sound:Dynamic, ?filter_text:Dynamic, ?filter_btx:Dynamic, ?filter_collada:Dynamic, ?filter_alembic:Dynamic, ?filter_folder:Dynamic, ?filter_blenlib:Dynamic, ?filemode:Dynamic, ?display_type:Dynamic, ?sort_method:Dynamic, ?import_units:Dynamic, ?fix_orientation:Dynamic, ?find_chains:Dynamic, ?auto_connect:Dynamic, ?min_chain_length:Dynamic, ?keep_bind_info:Dynamic):Dynamic;
	static public function context_collection_boolean_set(?data_path_iter:Dynamic, ?data_path_item:Dynamic, ?type:Dynamic):Dynamic;
	static public function context_cycle_array(?data_path:Dynamic, ?reverse:Dynamic):Dynamic;
	static public function context_cycle_enum(?data_path:Dynamic, ?reverse:Dynamic, ?wrap:Dynamic):Dynamic;
	static public function context_cycle_int(?data_path:Dynamic, ?reverse:Dynamic, ?wrap:Dynamic):Dynamic;
	static public function context_menu_enum(?data_path:Dynamic):Dynamic;
	static public function context_modal_mouse(?data_path_iter:Dynamic, ?data_path_item:Dynamic, ?header_text:Dynamic, ?input_scale:Dynamic, ?invert:Dynamic, ?initial_x:Dynamic):Dynamic;
	static public function context_pie_enum(?data_path:Dynamic):Dynamic;
	static public function context_scale_float(?data_path:Dynamic, ?value:Dynamic):Dynamic;
	static public function context_scale_int(?data_path:Dynamic, ?value:Dynamic, ?always_step:Dynamic):Dynamic;
	static public function context_set_boolean(?data_path:Dynamic, ?value:Dynamic):Dynamic;
	static public function context_set_enum(?data_path:Dynamic, ?value:Dynamic):Dynamic;
	static public function context_set_float(?data_path:Dynamic, ?value:Dynamic, ?relative:Dynamic):Dynamic;
	static public function context_set_id(?data_path:Dynamic, ?value:Dynamic):Dynamic;
	static public function context_set_int(?data_path:Dynamic, ?value:Dynamic, ?relative:Dynamic):Dynamic;
	static public function context_set_string(?data_path:Dynamic, ?value:Dynamic):Dynamic;
	static public function context_set_value(?data_path:Dynamic, ?value:Dynamic):Dynamic;
	static public function context_toggle(?data_path:Dynamic):Dynamic;
	static public function context_toggle_enum(?data_path:Dynamic, ?value_1:Dynamic, ?value_2:Dynamic):Dynamic;
	static public function copy_prev_settings():Dynamic;
	static public function debug_menu(?debug_value:Dynamic):Dynamic;
	static public function doc_view(?doc_id:Dynamic):Dynamic;
	static public function doc_view_manual(?doc_id:Dynamic):Dynamic;
	static public function doc_view_manual_ui_context():Dynamic;
	static public function interaction_preset_add(?name:Dynamic, ?remove_name:Dynamic, ?remove_active:Dynamic):Dynamic;
	static public function interface_theme_preset_add(?name:Dynamic, ?remove_name:Dynamic, ?remove_active:Dynamic):Dynamic;
	static public function keyconfig_activate(?filepath:Dynamic):Dynamic;
	static public function keyconfig_export(?all:Dynamic, ?filepath:Dynamic, ?filter_folder:Dynamic, ?filter_text:Dynamic, ?filter_python:Dynamic):Dynamic;
	static public function keyconfig_import(?filepath:Dynamic, ?filter_folder:Dynamic, ?filter_text:Dynamic, ?filter_python:Dynamic, ?keep_original:Dynamic):Dynamic;
	static public function keyconfig_preset_add(?name:Dynamic, ?remove_name:Dynamic, ?remove_active:Dynamic):Dynamic;
	static public function keyconfig_remove():Dynamic;
	static public function keyconfig_test():Dynamic;
	static public function keyitem_add():Dynamic;
	static public function keyitem_remove(?item_id:Dynamic):Dynamic;
	static public function keyitem_restore(?item_id:Dynamic):Dynamic;
	static public function keymap_restore(?all:Dynamic):Dynamic;
	static public function lib_reload(?library:Dynamic, ?filepath:Dynamic, ?directory:Dynamic, ?filename:Dynamic, ?filter_blender:Dynamic, ?filter_backup:Dynamic, ?filter_image:Dynamic, ?filter_movie:Dynamic, ?filter_python:Dynamic, ?filter_font:Dynamic, ?filter_sound:Dynamic, ?filter_text:Dynamic, ?filter_btx:Dynamic, ?filter_collada:Dynamic, ?filter_alembic:Dynamic, ?filter_folder:Dynamic, ?filter_blenlib:Dynamic, ?filemode:Dynamic, ?relative_path:Dynamic, ?display_type:Dynamic, ?sort_method:Dynamic):Dynamic;
	static public function lib_relocate(?library:Dynamic, ?filepath:Dynamic, ?directory:Dynamic, ?filename:Dynamic, ?files:Dynamic, ?filter_blender:Dynamic, ?filter_backup:Dynamic, ?filter_image:Dynamic, ?filter_movie:Dynamic, ?filter_python:Dynamic, ?filter_font:Dynamic, ?filter_sound:Dynamic, ?filter_text:Dynamic, ?filter_btx:Dynamic, ?filter_collada:Dynamic, ?filter_alembic:Dynamic, ?filter_folder:Dynamic, ?filter_blenlib:Dynamic, ?filemode:Dynamic, ?relative_path:Dynamic, ?display_type:Dynamic, ?sort_method:Dynamic):Dynamic;
	static public function link(?filepath:Dynamic, ?directory:Dynamic, ?filename:Dynamic, ?files:Dynamic, ?filter_blender:Dynamic, ?filter_backup:Dynamic, ?filter_image:Dynamic, ?filter_movie:Dynamic, ?filter_python:Dynamic, ?filter_font:Dynamic, ?filter_sound:Dynamic, ?filter_text:Dynamic, ?filter_btx:Dynamic, ?filter_collada:Dynamic, ?filter_alembic:Dynamic, ?filter_folder:Dynamic, ?filter_blenlib:Dynamic, ?filemode:Dynamic, ?relative_path:Dynamic, ?display_type:Dynamic, ?sort_method:Dynamic, ?link:Dynamic, ?autoselect:Dynamic, ?active_collection:Dynamic, ?instance_collections:Dynamic):Dynamic;
	static public function memory_statistics():Dynamic;
	static public function open_mainfile(?filepath:Dynamic, ?filter_blender:Dynamic, ?filter_backup:Dynamic, ?filter_image:Dynamic, ?filter_movie:Dynamic, ?filter_python:Dynamic, ?filter_font:Dynamic, ?filter_sound:Dynamic, ?filter_text:Dynamic, ?filter_btx:Dynamic, ?filter_collada:Dynamic, ?filter_alembic:Dynamic, ?filter_folder:Dynamic, ?filter_blenlib:Dynamic, ?filemode:Dynamic, ?display_type:Dynamic, ?sort_method:Dynamic, ?load_ui:Dynamic, ?use_scripts:Dynamic):Dynamic;
	static public function operator_cheat_sheet():Dynamic;
	static public function operator_defaults():Dynamic;
	static public function operator_pie_enum(?data_path:Dynamic, ?prop_string:Dynamic):Dynamic;
	static public function operator_preset_add(?name:Dynamic, ?remove_name:Dynamic, ?remove_active:Dynamic, ?operator:Dynamic):Dynamic;
	static public function owner_disable(?owner_id:Dynamic):Dynamic;
	static public function owner_enable(?owner_id:Dynamic):Dynamic;
	static public function path_open(?filepath:Dynamic):Dynamic;
	static public function previews_batch_clear(?files:Dynamic, ?directory:Dynamic, ?filter_blender:Dynamic, ?filter_folder:Dynamic, ?use_scenes:Dynamic, ?use_collections:Dynamic, ?use_objects:Dynamic, ?use_intern_data:Dynamic, ?use_trusted:Dynamic, ?use_backups:Dynamic):Dynamic;
	static public function previews_batch_generate(?files:Dynamic, ?directory:Dynamic, ?filter_blender:Dynamic, ?filter_folder:Dynamic, ?use_scenes:Dynamic, ?use_collections:Dynamic, ?use_objects:Dynamic, ?use_intern_data:Dynamic, ?use_trusted:Dynamic, ?use_backups:Dynamic):Dynamic;
	static public function previews_clear(?id_type:Dynamic):Dynamic;
	static public function previews_ensure():Dynamic;
	static public function properties_add(?data_path:Dynamic):Dynamic;
	static public function properties_context_change(?context:Dynamic):Dynamic;
	static public function properties_edit(?data_path:Dynamic, ?property:Dynamic, ?value:Dynamic, ?min:Dynamic, ?max:Dynamic, ?use_soft_limits:Dynamic, ?is_overridable_static:Dynamic, ?soft_min:Dynamic, ?soft_max:Dynamic, ?description:Dynamic):Dynamic;
	static public function properties_remove(?data_path:Dynamic, ?property:Dynamic):Dynamic;
	static public function quit_blender():Dynamic;
	static public function radial_control(?data_path_primary:Dynamic, ?data_path_secondary:Dynamic, ?use_secondary:Dynamic, ?rotation_path:Dynamic, ?color_path:Dynamic, ?fill_color_path:Dynamic, ?fill_color_override_path:Dynamic, ?fill_color_override_test_path:Dynamic, ?zoom_path:Dynamic, ?image_id:Dynamic, ?secondary_tex:Dynamic):Dynamic;
	static public function read_factory_settings(?app_template:Dynamic, ?use_empty:Dynamic):Dynamic;
	static public function read_history():Dynamic;
	static public function read_homefile(?filepath:Dynamic, ?load_ui:Dynamic, ?use_empty:Dynamic, ?use_splash:Dynamic, ?app_template:Dynamic):Dynamic;
	static public function recover_auto_save(?filepath:Dynamic, ?filter_blender:Dynamic, ?filter_backup:Dynamic, ?filter_image:Dynamic, ?filter_movie:Dynamic, ?filter_python:Dynamic, ?filter_font:Dynamic, ?filter_sound:Dynamic, ?filter_text:Dynamic, ?filter_btx:Dynamic, ?filter_collada:Dynamic, ?filter_alembic:Dynamic, ?filter_folder:Dynamic, ?filter_blenlib:Dynamic, ?filemode:Dynamic, ?display_type:Dynamic, ?sort_method:Dynamic):Dynamic;
	static public function recover_last_session():Dynamic;
	static public function redraw_timer(?type:Dynamic, ?iterations:Dynamic, ?time_limit:Dynamic):Dynamic;
	static public function revert_mainfile(?use_scripts:Dynamic):Dynamic;
	static public function save_as_mainfile(?filepath:Dynamic, ?check_existing:Dynamic, ?filter_blender:Dynamic, ?filter_backup:Dynamic, ?filter_image:Dynamic, ?filter_movie:Dynamic, ?filter_python:Dynamic, ?filter_font:Dynamic, ?filter_sound:Dynamic, ?filter_text:Dynamic, ?filter_btx:Dynamic, ?filter_collada:Dynamic, ?filter_alembic:Dynamic, ?filter_folder:Dynamic, ?filter_blenlib:Dynamic, ?filemode:Dynamic, ?display_type:Dynamic, ?sort_method:Dynamic, ?compress:Dynamic, ?relative_remap:Dynamic, ?copy:Dynamic):Dynamic;
	static public function save_homefile():Dynamic;
	static public function save_mainfile(?filepath:Dynamic, ?check_existing:Dynamic, ?filter_blender:Dynamic, ?filter_backup:Dynamic, ?filter_image:Dynamic, ?filter_movie:Dynamic, ?filter_python:Dynamic, ?filter_font:Dynamic, ?filter_sound:Dynamic, ?filter_text:Dynamic, ?filter_btx:Dynamic, ?filter_collada:Dynamic, ?filter_alembic:Dynamic, ?filter_folder:Dynamic, ?filter_blenlib:Dynamic, ?filemode:Dynamic, ?display_type:Dynamic, ?sort_method:Dynamic, ?compress:Dynamic, ?relative_remap:Dynamic, ?exit:Dynamic):Dynamic;
	static public function save_userpref():Dynamic;
	static public function search_menu():Dynamic;
	static public function set_stereo_3d(?display_mode:Dynamic, ?anaglyph_type:Dynamic, ?interlace_type:Dynamic, ?use_interlace_swap:Dynamic, ?use_sidebyside_crosseyed:Dynamic):Dynamic;
	static public function splash():Dynamic;
	static public function studiolight_install(?files:Dynamic, ?directory:Dynamic, ?filter_folder:Dynamic, ?filter_glob:Dynamic, ?orientation:Dynamic):Dynamic;
	static public function studiolight_uninstall(?index:Dynamic):Dynamic;
	static public function studiolight_userpref_show():Dynamic;
	static public function sysinfo(?filepath:Dynamic):Dynamic;
	static public function theme_install(?overwrite:Dynamic, ?filepath:Dynamic, ?filter_folder:Dynamic, ?filter_glob:Dynamic):Dynamic;
	static public function tool_set_by_name(?name:Dynamic, ?cycle:Dynamic, ?space_type:Dynamic):Dynamic;
	static public function toolbar():Dynamic;
	static public function url_open(?url:Dynamic):Dynamic;
	static public function userpref_autoexec_path_add():Dynamic;
	static public function userpref_autoexec_path_remove(?index:Dynamic):Dynamic;
	static public function window_close():Dynamic;
	static public function window_fullscreen_toggle():Dynamic;
	static public function window_new():Dynamic;
	static public function window_new_main():Dynamic;
}