/* This file is generated, do not edit! */
package bpy.ops.pose;
@:pythonImport("bpy.ops.pose") extern class Pose_Module {
	static public var __builtins__ : Dynamic;
	static public var __cached__ : Dynamic;
	static public var __doc__ : Dynamic;
	static public var __file__ : Dynamic;
	static public var __loader__ : Dynamic;
	static public var __name__ : Dynamic;
	static public var __package__ : Dynamic;
	static public var __spec__ : Dynamic;
	static public function armature_apply():Dynamic;
	static public function autoside_names(?axis:Dynamic):Dynamic;
	static public function bone_layers(?layers:Dynamic):Dynamic;
	static public function breakdown(?percentage:Dynamic, ?prev_frame:Dynamic, ?next_frame:Dynamic, ?channels:Dynamic, ?axis_lock:Dynamic):Dynamic;
	static public function constraint_add(?type:Dynamic):Dynamic;
	static public function constraint_add_with_targets(?type:Dynamic):Dynamic;
	static public function constraints_clear():Dynamic;
	static public function constraints_copy():Dynamic;
	static public function copy():Dynamic;
	static public function flip_names(?do_strip_numbers:Dynamic):Dynamic;
	static public function group_add():Dynamic;
	static public function group_assign(?type:Dynamic):Dynamic;
	static public function group_deselect():Dynamic;
	static public function group_move(?direction:Dynamic):Dynamic;
	static public function group_remove():Dynamic;
	static public function group_select():Dynamic;
	static public function group_sort():Dynamic;
	static public function group_unassign():Dynamic;
	static public function hide(?unselected:Dynamic):Dynamic;
	static public function ik_add(?with_targets:Dynamic):Dynamic;
	static public function ik_clear():Dynamic;
	static public function loc_clear():Dynamic;
	static public function paste(?flipped:Dynamic, ?selected_mask:Dynamic):Dynamic;
	static public function paths_calculate(?start_frame:Dynamic, ?end_frame:Dynamic, ?bake_location:Dynamic):Dynamic;
	static public function paths_clear(?only_selected:Dynamic):Dynamic;
	static public function paths_range_update():Dynamic;
	static public function paths_update():Dynamic;
	static public function propagate(?mode:Dynamic, ?end_frame:Dynamic):Dynamic;
	static public function push(?percentage:Dynamic, ?prev_frame:Dynamic, ?next_frame:Dynamic, ?channels:Dynamic, ?axis_lock:Dynamic):Dynamic;
	static public function quaternions_flip():Dynamic;
	static public function relax(?percentage:Dynamic, ?prev_frame:Dynamic, ?next_frame:Dynamic, ?channels:Dynamic, ?axis_lock:Dynamic):Dynamic;
	static public function reveal(?select:Dynamic):Dynamic;
	static public function rot_clear():Dynamic;
	static public function rotation_mode_set(?type:Dynamic):Dynamic;
	static public function scale_clear():Dynamic;
	static public function select_all(?action:Dynamic):Dynamic;
	static public function select_constraint_target():Dynamic;
	static public function select_grouped(?extend:Dynamic, ?type:Dynamic):Dynamic;
	static public function select_hierarchy(?direction:Dynamic, ?extend:Dynamic):Dynamic;
	static public function select_linked(?extend:Dynamic):Dynamic;
	static public function select_mirror(?only_active:Dynamic, ?extend:Dynamic):Dynamic;
	static public function select_parent():Dynamic;
	static public function transforms_clear():Dynamic;
	static public function user_transforms_clear(?only_selected:Dynamic):Dynamic;
	static public function visual_transform_apply():Dynamic;
}